from typing import Any, Protocol


class BrowserAuthPort(Protocol):
    def local_binding(self, actor: str, project: str) -> list[str]: ...
    def issue_local(self, actor: str, project: str) -> str: ...
    def register(self, username: str, password: str, peer: str) -> str: ...
    def login(self, username: str, password: str, peer: str) -> str: ...
    def detail(self, token: str) -> tuple[dict[str, Any], list[str]]: ...
    def logout(self, token: str) -> None: ...
