"""Server-owned frozen route context; no second planner or lifecycle."""
from typing import Protocol


class GeneratedPlanChangesPort(Protocol):
    def existing_submission(self, scope, command): ...
    def prepare(self, scope, command): ...
    def validate_generation(self, scope, metadata): ...
    def save_generated(self, scope, metadata, draft, write_fence=None): ...
