"""Atomic private resource selection and durable search reservation boundary."""
from typing import Protocol

from app.domain.workspace.models import AuthContext


class LearningResourcesPort(Protocol):
    def reserve(self, scope: AuthContext, target: dict, query: str, key: str,
                input_hash: str, limit: int) -> tuple[dict, bool]: ...
    def finish(self, scope: AuthContext, target: dict, search_id: str, status: str,
               candidates: list[dict], error: str | None) -> dict: ...
    def get_search(self, scope: AuthContext, target: dict, search_id: str) -> dict: ...
    def get_search_by_key(self, scope: AuthContext, target: dict, key: str) -> dict: ...
    def list_selected(self, scope: AuthContext, target: dict) -> list[dict]: ...
    def select(self, scope: AuthContext, target: dict, resource: dict) -> dict: ...
    def remove(self, scope: AuthContext, target: dict, selection_id: str) -> bool: ...
