"""Atomic private resource selection and durable search reservation boundary."""
from typing import Protocol

from app.domain.workspace.models import AuthContext


class LearningResourcesPort(Protocol):
    def reserve(self, scope: AuthContext, target: dict, query: str, key: str,
                input_hash: str, limit: int, *, source: str = "web", context_snapshot: dict | None = None) -> tuple[dict, bool]: ...
    def check_search_intent(self, scope: AuthContext, target: dict, key: str, input_hash: str) -> None: ...
    def finish(self, scope: AuthContext, target: dict, search_id: str, status: str,
               candidates: list[dict], error: str | None) -> dict: ...
    def get_search(self, scope: AuthContext, target: dict, search_id: str) -> dict: ...
    def get_search_by_key(self, scope: AuthContext, target: dict, key: str) -> dict: ...
    def reserve_inspection(self, scope: AuthContext, target: dict, search_id: str, candidate_id: str,
                           key: str, input_hash: str, paths: list[str], context_snapshot: dict,
                           content_limit: int, metadata_limit: int) -> tuple[dict, bool]: ...
    def finish_inspection(self, scope: AuthContext, target: dict, inspection_id: str, status: str,
                          candidate: dict | None, receipts: list[dict], error: str | None) -> dict: ...
    def get_inspection(self, scope: AuthContext, target: dict, inspection_id: str) -> dict: ...
    def get_inspection_by_key(self, scope: AuthContext, target: dict, key: str) -> dict: ...
    def latest_inspection(self, scope: AuthContext, target: dict, search_id: str, candidate_id: str) -> dict | None: ...
    def allowed_module_keys(self, scope: AuthContext, target: dict) -> list[str]: ...
    def list_selected(self, scope: AuthContext, target: dict) -> list[dict]: ...
    def select(self, scope: AuthContext, target: dict, resource: dict) -> dict: ...
    def remove(self, scope: AuthContext, target: dict, selection_id: str) -> bool: ...
