from typing import Protocol


class PromptsPort(Protocol):
    def thread(self, scope, project_id, plan_id, stage_id, task_id) -> dict: ...
    def save(self, scope, command) -> dict: ...
    def attempt(self, scope, project_id, revision_id) -> dict: ...
    def history(self, scope, project_id, cursor=None, limit=20) -> dict: ...
    def review_receipt(self, scope, project_id, revision_id, key) -> dict | None: ...
    def has_review_binding(self, scope, project_id, revision_id) -> bool: ...
    def enqueue_review(self, scope, project_id, revision_id, key, manifest) -> dict: ...
    def cancel_review(self, scope, project_id, revision_id, run_id, expected_version, key) -> dict: ...
    def review_submission(self, claim) -> dict: ...
    def finish_review(self, claim, revision_id, review=None, *, error_class=None, unknown=False) -> str: ...
    def export(self, scope, project_id, revision_id, format, key) -> dict: ...
    def get_export(self, scope, project_id, export_id) -> dict: ...
