from typing import Protocol


class ResourceChangeRepository(Protocol):
    def catalog(self, scope, project_id): ...
    def preview(self, scope, command): ...
    def get(self, scope, project_id, proposal_id): ...
    def decide(self, scope, project_id, proposal_id, action, expected_version, preview_hash, idempotency_key,
               acknowledge_warnings=False): ...
