from typing import Protocol


class ReviewPersistenceInterrupted(RuntimeError):
    """Leave the durable job recoverable; the ledger controls replay or reconcile."""


class SummariesPort(Protocol):
    def thread(self, scope, project_id, plan_id, stage_id, unit_id=None) -> dict: ...
    def save(self, scope, command) -> dict: ...
    def attempt(self, scope, project_id, attempt_id) -> dict: ...
    def review_receipt(self, scope, project_id, attempt_id, key) -> dict | None: ...
    def has_review_binding(self, scope, project_id, attempt_id) -> bool: ...
    def history(self, scope, project_id, cursor=None, limit=20) -> dict: ...
    def enqueue_review(self, scope, project_id, attempt_id, key, manifest) -> dict: ...
    def cancel_review(self, scope, project_id, attempt_id, run_id, expected_version, key) -> dict: ...
    def review_submission(self, claim) -> dict: ...
    def finish_review(self, claim, attempt_id, review=None, *, error_class=None, unknown=False) -> str: ...
