"""Item8 transaction port; existing plans and publication remain authoritative."""
from typing import Protocol


class V2RevisionsPort(Protocol):
    def context(self, **kwargs): ...
    def preview_local(self, **kwargs): ...
    def get_preview(self, **kwargs): ...
    def confirm(self, **kwargs): ...
    def cancel(self, **kwargs): ...
    def submit_semantic(self, **kwargs): ...
