import { useState } from 'react';
import type { PlanningDraft, PlanningPlan } from '../../api/client';
import { fact, facts, lines, text, resourceTitle, safeUrl, serverGoal, constraintStatus, unresolvedOutcomes, type Fact } from './facts';
import { PlanningDialog } from './PlanningDialog';
function List({ value }: {
    value: unknown;
}) { const items = lines(value); return items.length ? <ul>{items.map((item, i) => <li key={i}>{item}</li>)}</ul> : null; }
function Resource({ item, onOpen }: {
    item: Fact;
    onOpen: (item: Fact) => void;
}) { const source = fact(item.source_snapshot); return <div className="pv-resource"><span className="pv-role">{({ primary: '核心教材 · Primary', supplement: '补充材料 · Supplement', reference: '查阅资料 · Reference' } as Record<string, string>)[text(item.role)] || '学习资料'}</span><button className="text-button" onClick={() => onOpen(item)}>{resourceTitle(source.title, source.url)}</button><p>{text(item.reading_focus)}</p><List value={source.section_refs}/><List value={source.limitations}/></div>; }
export function Curriculum({ plan }: {
    plan: PlanningDraft | PlanningPlan;
}) {
    const goal = serverGoal(plan);
    const content = fact(plan.v2_content), stages = facts(content.stages), practice = fact(content.practice), carrier = fact(practice.carrier);
    const [resource, setResource] = useState<Fact | null>(null), [collapse, setCollapse] = useState(0);
    const titleById = new Map(stages.map(s => [text(s.stage_id), text(s.title)]));
    const final = fact(practice.final_artifact || carrier.final_artifact);
    return <><section className="pv-panel"><h2>{plan.goal_snapshot}</h2>{goal.starting_point && <p><strong>当前起点：</strong>{goal.starting_point}</p>}<List value={goal.constraints}/><p><strong>主要学习能力：</strong>{facts(fact(content.capabilities).capabilities).filter(c => c.disposition === "needs_learning").map(c => text(c.title)).join("、")}</p>{text(carrier.description) && <div className="pv-project-line"><h3>{carrier.kind === 'user_project' ? '继续使用你的项目' : '贯穿实践项目'}</h3><p>{text(carrier.description)}</p><p className="pv-muted">{text(carrier.reason)}</p></div>}</section>
 {plan.v2_content && <section className="pv-panel"><h3>目标与学习边界</h3><List value={fact(content.profile).required_requirements}/><List value={fact(content.profile).scope}/><p>深度：{({unspecified:'暂不指定',foundation:'理解基础',applied:'能够应用',deep:'深入理解'} as Record<string,string>)[text(fact(content.profile).desired_depth)] || '以保存的目标为准'}</p>{facts(fact(content.capabilities).capabilities).map((cap,i)=><div key={i}><p><strong>{text(cap.title)}</strong>：{cap.disposition === 'accepted_known' ? '已有基础声明保留，不安排为新的学习任务' : cap.disposition === 'needs_learning' ? '需要学习' : '以当前能力安排为准'}；{cap.disposition === 'accepted_known' ? '目标所需的已有基础，不重新安排学习' : cap.learning_requirement === 'required' ? '属于必要学习范围' : cap.learning_requirement === 'recommended' ? '推荐学习' : '学习安排以当前目标为准'}；{cap.project_usage === 'excluded' ? '不用于贯穿项目，通过独立练习学习' : cap.project_usage === 'required' ? '需要用于项目实践' : cap.project_usage === 'optional' ? '项目使用可选' : '项目使用按阶段事实安排'}</p><h4>{cap.disposition === 'accepted_known' ? '已有能力说明' : '具体学习能力'}</h4><List value={cap.learning_outcomes}/></div>)}</section>} {facts(content.materials).some(m => lines(fact(m.source_snapshot).limitations).some(note => /synthetic fixture/i.test(note))) && <p className="pv-notice pv-warning">材料包含合成验收资料，这份展示不代表真实课程质量已验收。</p>}
 {!plan.v2_content && <p className="pv-notice">此历史版本没有完整的新版教材与实践快照，以下只显示保存的阶段事实。</p>}
 <div className="pv-section-head"><h2>分阶段学习路线</h2><button className="text-button" onClick={() => setCollapse(v => v + 1)}>收起全部阶段</button></div>
 {(stages.length ? stages : facts(plan.stages)).map((stage, index) => {
            const id = text(stage.stage_id), guidance = fact(stage.guidance);
            return <details className="pv-stage" key={`${id}:${collapse}`}><summary><span className="pv-number">{index + 1}</span><span><strong>{text(stage.title)}</strong><span className="pv-summary">{text(stage.what_to_learn || stage.objective)}</span><span className="pv-summary">{text(stage.why_now || guidance.why_now)}</span><span className="pv-summary">知识：{facts(content.knowledge).filter(n => n.stage_ref === id).map(n => text(n.title)).join("、")}</span><span className="pv-summary">核心教材：{facts(content.materials).filter(m => m.stage_ref === id && m.role === "primary").map(m => `${resourceTitle(fact(m.source_snapshot).title, fact(m.source_snapshot).url)}：${text(m.reading_focus)} ${lines(fact(m.source_snapshot).section_refs).join("、")}`).join("；")}</span><span className="pv-summary">实践：{facts(practice.tasks).filter(t => t.stage_ref === id).map(t => `${t.practice_kind === "micro_exercise" ? "独立小练习" : "项目增量"}：${text(t.title)}`).join("；")}</span></span></summary><div className="pv-stage-body"><p>{text(guidance.previous_relation)}</p>{lines(stage.prerequisite_stage_refs).length > 0 && <p>前置阶段：{lines(stage.prerequisite_stage_refs).map(ref => titleById.get(ref) || '对应前置阶段').join('、')}</p>}<List value={guidance.learning_focus}/><List value={guidance.comparison_focus}/>
 {facts(content.knowledge).filter(n => n.stage_ref === id).map((node, i) => <section key={i}><h3>{text(node.title)}</h3><List value={node.objectives}/></section>)}
 {facts(content.units).filter(u => u.stage_ref === id).map((unit, i) => <details className="pv-unit" key={i}><summary>{text(unit.title) || '学习单元'}</summary><List value={unit.objectives}/><h4>单元验收</h4><List value={unit.rubric}/></details>)}
 <h3>教材与阅读范围</h3>{facts(content.materials).filter(r => r.stage_ref === id).map((r, i) => <Resource key={i} item={r} onOpen={setResource}/>)}
 {facts(practice.tasks).filter(t => t.stage_ref === id).map((task, i) => <section className="pv-practice" key={i}><h3>{task.practice_kind === 'micro_exercise' ? '独立小练习 · Micro Exercise' : '项目阶段实践'}：{text(task.title)}</h3><p>{text(task.goal)}</p><h4>实施范围</h4><List value={task.in_scope}/>{lines(task.out_scope).length > 0 && <><h4>本次不包含</h4><List value={task.out_scope}/></>}<h4>交付与验收</h4><List value={task.acceptance}/></section>)}
 {Object.keys(fact(guidance.practice_delta)).length > 0 && <section className="pv-practice"><h3>实践衔接与保留边界</h3>{(['baseline', 'increment', 'preserved', 'reuse', 'validation'] as const).map(k => <div key={k}><strong>{{ baseline: '起点', increment: '本阶段增量', preserved: '保留的行为', reuse: '迁回已有项目', validation: '验证要求' }[k]}</strong>{typeof fact(guidance.practice_delta)[k] === 'string' ? <p>{text(fact(guidance.practice_delta)[k])}</p> : <List value={fact(guidance.practice_delta)[k]}/>}</div>)}</section>}
 {facts(content.project_study).filter(s => lines(stage.project_study_refs).includes(text(fact(s.requirement).requirement_id))).map((study, i) => { const requirement = fact(study.requirement), source = fact(study.case); return <details className="pv-unit" key={i}><summary>项目源码学习：{text(requirement.problem)}</summary><p>{requirement.mode === 'whole_core' ? '学习工程核心整体' : '学习相关工程切片'}</p><h4>正常行为</h4><List value={requirement.normal_behavior}/><h4>失败路径</h4><List value={requirement.failure_behavior}/>{facts(requirement.inputs_outputs).map((pair, n) => <p key={n}>输入：{text(pair.input)}；输出：{text(pair.output)}</p>)}<h4>设计问题</h4><List value={requirement.design_questions}/><h4>学习产物</h4><List value={requirement.expected_outputs}/><h4>不阅读的范围</h4><List value={requirement.avoid_scope}/><p>源码版本：{text(source.version)}</p><List value={source.limitations}/>{safeUrl(source.repo_url) && <a href={safeUrl(source.repo_url)} target="_blank" rel="noreferrer">查看源码来源</a>}<p className="pv-muted">这是对别人项目的源码学习，与你自己的持续实践分别记录。</p></details>; })} </div></details>;
        })}
 {Object.keys(final).length > 0 && <section className="pv-panel"><h2>最终成果</h2><p>{text(final.description)}</p><List value={final.acceptance}/></section>}
 {Object.keys(fact(content.constraints)).length > 0 && <section className="pv-panel"><h3>限制与核实依据</h3><List value={fact(content.constraints).hard_constraints}/>{facts(fact(content.constraints).assessments).map((assessment,i)=><p key={i}>{assessment.scope === "material_access" ? "教材访问限制" : "目标限制"}：{constraintStatus(assessment)}。{assessment.reason === "all_selected_materials_verified_free" ? "所选材料的免费访问条件已核对。" : assessment.reason === "access_unproven" ? "访问条件的依据尚未齐全。" : "核实依据保留在当前计划中。"}</p>)}</section>}{unresolvedOutcomes(content).length > 0 && <section className="pv-panel pv-warning"><h3>仍待补齐的学习目标</h3><ul>{unresolvedOutcomes(content).map((item, i) => <li key={i}><strong>{item.title}</strong>{item.reason && <>：{item.reason}</>}</li>)}</ul></section>}<List value={content.source_limitations}/>
 {resource && <PlanningDialog title={resourceTitle(fact(resource.source_snapshot).title, fact(resource.source_snapshot).url)} onClose={() => setResource(null)}><p>{text(resource.reading_focus)}</p><h3>指定阅读范围</h3><List value={fact(resource.source_snapshot).section_refs}/><p>材料版本：{text(fact(resource.source_snapshot).source_version) || '未提供'}</p><List value={fact(resource.source_snapshot).limitations}/>{safeUrl(fact(resource.source_snapshot).url) && <a href={safeUrl(fact(resource.source_snapshot).url)} target="_blank" rel="noreferrer">打开来源材料</a>}<p className="pv-muted">阅读位置和材料版本以此份计划保存的事实为准。</p><button onClick={() => setResource(null)}>关闭</button></PlanningDialog>}</>;
}
