const {chromium}=require('playwright-core');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage();page.setDefaultTimeout(4000);
 const stage={stage_id:'s',stable_key:'stage.tools',title:'工具阶段',order_index:0,section_kind:'core',objective:'工具'};
 const knowledge=[{node_id:'n',stable_key:'tools',title:'工具调用',content_version:1},{node_id:'n2',stable_key:'errors',title:'错误处理',content_version:2}];
 const task={task_id:'t',practice_project_id:'pp',stable_key:'task.tools',version:1,stage_id:'s',stage_key:'stage.tools',order_index:0,title:'原任务',goal:'实现工具助手',in_scope:['工具协议'],out_scope:['公网部署'],acceptance:['可解释结果'],status:'pending',knowledge_links:[{...knowledge[0],role:'core'}]};
 const practice={practice_project_id:'pp',title:'候选主项目',idea:'围绕工具协议完成一个可检查的助手',repo_url:null,status:'idea',version:1};
 let workspace={plan:{plan_id:'p',project_id:'project',revision:1,goal_snapshot:'学习目标',stages:[stage],unit_links:[],task_links:[],stage_resources:[],extensions:[]},stages:[{stage,nodes:[],units:[],resources:[],tasks:[task]}],total_units:0,completed_units:0};
 let context={project_id:'project',plan_id:'p',revision:1,version:1,practice_projects:[practice],stages:[stage],tasks:[task],knowledge_options:knowledge};
 const previews=[],confirms=[],cancels=[];let failPreview=true,failConfirm=true,failCancel=true,conflict=false,invalid=false,proposal,modelCalls=0;
 await page.addInitScript(()=>{navigator.clipboard.writeText=async text=>{window.practiceCopied=text;};});
 await page.route('**/api/v1/**',r=>{modelCalls++;return r.abort('blockedbyclient');});
 await page.route('**/api/v1/session',r=>r.fulfill({json:{username:'实践用户',project_ids:['project'],csrf_token:'test-csrf'}}));
 await page.route('**/healthz',r=>r.fulfill({json:{llm_provider:'fake'}}));
 await page.route('**/api/v1/workspace?**',r=>r.fulfill({json:workspace}));
 await page.route('**/api/v1/prompts**',r=>{const u=new URL(r.request().url());return r.fulfill({json:u.pathname.endsWith('/history')?{items:[],next_cursor:null}:{project_id:'project',plan_id:workspace.plan.plan_id,stage_id:'s',task_id:workspace.stages[0].tasks[0].task_id,version:0,practice_project:practice,task:workspace.stages[0].tasks[0],revisions:[],history_truncated:false}});});
 await page.route('**/api/v1/practice-changes**',r=>{
  const req=r.request(),url=new URL(req.url());if(req.method()==='GET')return r.fulfill({json:url.pathname.endsWith('/context')?context:proposal});
  assert.equal(req.headers()['x-csrf-token'],'test-csrf');const body=req.postDataJSON();
  if(url.pathname.endsWith('/confirm')){confirms.push(body);if(failConfirm){failConfirm=false;return r.abort('failed');}proposal.status='confirmed';const newStage={...stage,stage_id:'s2'},newTask={...task,task_id:'new-t',practice_project_id:'pp2',stage_id:'s2',title:'新任务'};workspace={...workspace,plan:{...workspace.plan,plan_id:'p2',revision:2,stages:[newStage]},stages:[{...workspace.stages[0],stage:newStage,tasks:[newTask]}]};context={...context,plan_id:'p2',revision:2,version:2,practice_projects:[{...practice,practice_project_id:'pp2'}],stages:[newStage],tasks:[newTask]};return r.fulfill({json:{proposal_id:proposal.proposal_id,action:'confirm',status:'confirmed',plan_id:'p2',revision:2,created:true,copied_selections:1}});}
  if(url.pathname.endsWith('/cancel')){cancels.push(body);if(failCancel){failCancel=false;return r.abort('failed');}proposal.status='cancelled';return r.fulfill({json:{proposal_id:proposal.proposal_id,action:'cancel',status:'cancelled',plan_id:null,revision:null,created:false,copied_selections:0}});}
  previews.push(body);if(conflict){conflict=false;return r.fulfill({status:409,json:{message:'当前路线已变化'}});}if(invalid){invalid=false;return r.fulfill({status:422,json:{message:'仓库地址无效，请检查输入'}});}
  proposal={proposal_id:'proposal-'+previews.length,draft_id:'d',project_id:'project',base_plan_id:body.plan_id,base_revision:body.expected_version,base_version:body.expected_version,status:'pending',preview_hash:'previewhash',draft_hash:'drafthash',copy_policy:body.copy_policy,before:practice,after:{...practice,title:body.title,idea:body.idea,repo_url:body.repo_url},task_changes:body.task_changes.map(c=>({operation:c.operation,before:c.operation==='update'?task:null,after:{...task,...c,task_id:'candidate-'+c.client_key,knowledge_links:c.knowledge_links.map(link=>({...knowledge.find(n=>n.node_id===link.node_id),role:link.role}))}})),impact:{changed_task_ids:['t'],added_task_ids:['added'],cloned_task_count:2,started_task_count:0,prompt_revision_count:0,summary_count:0,exposure_count:1,private_binding_count:1,new_exposures_reset:true,preserve_history:true},warnings:['新任务从待开始状态开始；旧原文保留。'],created_at:new Date().toISOString()};
  if(failPreview){failPreview=false;return r.abort('failed');}return r.fulfill({json:proposal});
 });
 await page.goto((process.env.STUDYPLAN_URL||'http://127.0.0.1:5174')+'/#practice');
 const editor=page.getByRole('textbox',{name:'方案与 Prompt 原文',exact:true});await editor.waitFor();const raw='  旧路线未保存方案🙂\n不要改写。  ';await editor.fill(raw);
 await page.getByText('调整主项目与阶段任务',{exact:true}).click();await page.getByLabel('主项目标题',{exact:true}).waitFor();
 await page.getByLabel('主项目标题',{exact:true}).fill('我的自选项目');await page.getByLabel('主项目设想',{exact:true}).fill('按自己的目标设计工具助手与错误处理流程');await page.getByLabel('仓库地址（可选）').fill('https://example.com/my-repo');
 await page.getByRole('button',{name:'编辑任务：原任务',exact:true}).click();const update=page.getByRole('group',{name:'编辑任务 1',exact:true});await update.getByLabel('任务标题',{exact:true}).fill('修订任务');await update.getByLabel('交付物与任务目标',{exact:true}).fill('交付助手和故障说明');
 await update.getByLabel('选择知识：错误处理',{exact:true}).check();await update.getByLabel('知识角色：错误处理',{exact:true}).selectOption('supporting');
 await page.getByRole('button',{name:'添加阶段任务',exact:true}).click();const added=page.getByRole('group',{name:'编辑任务 2',exact:true});await added.getByLabel('任务标题',{exact:true}).fill('新增验证任务');await added.getByLabel('交付物与任务目标',{exact:true}).fill('交付可复现验证');for(const label of ['实施范围','范围之外','验收要求'])await added.getByLabel(label,{exact:true}).fill(label+'条目');await added.getByLabel('选择知识：工具调用',{exact:true}).check();await added.getByLabel('选择知识：错误处理',{exact:true}).check();await added.getByLabel('知识角色：错误处理',{exact:true}).selectOption('extension');
 await added.getByLabel('知识角色：工具调用',{exact:true}).selectOption('supporting');await page.getByRole('button',{name:'生成实践调整预览',exact:true}).click();await page.getByText(/每个修改任务至少关联一个核心知识/).waitFor();assert.equal(previews.length,0);await added.getByLabel('知识角色：工具调用',{exact:true}).selectOption('core');
 await page.getByLabel('私人资料沿用策略').selectOption('copy_active');await page.getByRole('button',{name:'生成实践调整预览',exact:true}).click();await page.getByRole('button',{name:'重试原预览',exact:true}).waitFor();await page.getByLabel('主项目标题',{exact:true}).fill('重试期间新标题');await page.getByRole('button',{name:'重试原预览',exact:true}).click();await page.getByRole('heading',{name:'实践调整预览',exact:true}).waitFor();assert.deepEqual(previews[0],previews[1]);assert.equal(previews[0].task_changes.length,2);assert.equal(previews[0].task_changes[1].task_id,null);assert.deepEqual(previews[0].task_changes[1].knowledge_links.map(n=>n.role),['core','extension']);assert.equal(await page.getByLabel('主项目标题',{exact:true}).inputValue(),'重试期间新标题');
 const preview=page.getByRole('region',{name:'实践调整预览',exact:true});await preview.getByText('交付助手和故障说明',{exact:true}).waitFor();await preview.getByText('错误处理（支撑）',{exact:true}).waitFor();const confirm=preview.getByRole('button',{name:'确认并发布实践调整',exact:true});assert.equal(await confirm.isEnabled(),false);await preview.getByRole('checkbox',{name:'我已阅读差异和全部提示，同意发布这次调整',exact:true}).check();await confirm.click();await preview.getByRole('button',{name:'重试原确认',exact:true}).waitFor();await page.getByLabel('主项目标题',{exact:true}).fill('确认期间的新输入');await preview.getByRole('button',{name:'重试原确认',exact:true}).click();await page.getByText(/已发布路线第 2 版/).waitFor();assert.deepEqual(confirms[0],confirms[1]);
 const recovery=page.getByRole('region',{name:'旧路线未保存的原文',exact:true});await recovery.waitFor();assert.equal(await recovery.getByRole('textbox').inputValue(),raw);assert.equal(await recovery.getByRole('textbox').getAttribute('readonly'),'');await recovery.getByRole('button',{name:'复制旧路线原文',exact:true}).click();assert.equal(await page.evaluate(()=>window.practiceCopied),raw);assert.equal(await editor.inputValue(),'');
 await page.getByRole('button',{name:'读取当前实践设计',exact:true}).click();assert.equal(await page.getByLabel('主项目标题',{exact:true}).inputValue(),'确认期间的新输入');
 await page.getByText('原主项目已不在当前路线，请明确选择当前主项目；本地文字会继续保留。',{exact:true}).waitFor();assert.equal(await page.getByLabel('选择主项目').inputValue(),'pp');assert.equal(await page.getByRole('button',{name:'生成实践调整预览',exact:true}).isEnabled(),false);
 await page.getByLabel('选择主项目').selectOption('pp2');assert.equal(await page.getByLabel('主项目标题',{exact:true}).inputValue(),'确认期间的新输入');
 await page.getByText('原阶段已不在当前路线，请明确选择当前阶段；已有任务编辑不会自动改归属。',{exact:true}).waitFor();assert.equal(await page.getByLabel('调整所属阶段').inputValue(),'s');assert.equal(await page.getByRole('button',{name:'添加阶段任务',exact:true}).isEnabled(),false);await page.getByLabel('调整所属阶段').selectOption('s2');
 await page.getByText('部分本地任务编辑仍属于旧路线，请保留文字后撤回这些编辑，再选择当前任务。',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'生成实践调整预览',exact:true}).isEnabled(),false);
 while(await page.getByRole('button',{name:'撤回这项本地编辑',exact:true}).count())await page.getByRole('button',{name:'撤回这项本地编辑',exact:true}).first().click();
 await page.getByRole('button',{name:'编辑任务：新任务',exact:true}).click();await page.getByRole('group',{name:'编辑任务 1',exact:true}).getByLabel('交付物与任务目标',{exact:true}).fill('第二次编辑仍保留自己的文字');
 conflict=true;await page.getByRole('button',{name:'生成实践调整预览',exact:true}).click();await page.getByText(/当前路线已变化/).first().waitFor();await page.getByRole('button',{name:'读取当前实践设计',exact:true}).click();assert.equal(await page.getByLabel('主项目标题',{exact:true}).inputValue(),'确认期间的新输入');
 await page.getByRole('button',{name:'生成实践调整预览',exact:true}).click();await preview.getByRole('button',{name:'取消这次调整',exact:true}).click();await preview.getByRole('button',{name:'重试原取消',exact:true}).click();await page.getByText('这次调整已取消，当前路线未被改变。',{exact:true}).waitFor();assert.deepEqual(cancels[0],cancels[1]);
 while(await page.getByRole('button',{name:'撤回这项本地编辑',exact:true}).count())await page.getByRole('button',{name:'撤回这项本地编辑',exact:true}).first().click();await page.getByLabel('主项目标题',{exact:true}).fill(practice.title);await page.getByLabel('主项目设想',{exact:true}).fill(practice.idea);await page.getByLabel('仓库地址（可选）').fill('');await page.getByRole('button',{name:'编辑任务：新任务',exact:true}).click();await page.getByRole('group',{name:'编辑任务 1',exact:true}).getByLabel('交付物与任务目标',{exact:true}).fill('仅修改这个任务的交付物');await page.getByRole('button',{name:'生成实践调整预览',exact:true}).click();await preview.getByText('仅修改这个任务的交付物',{exact:true}).waitFor();assert.equal(previews.at(-1).title,practice.title);assert.equal(previews.at(-1).task_changes.length,1);assert.equal(previews.at(-1).task_changes[0].task_id,'new-t');
 fs.mkdirSync(path.resolve(__dirname,'../../var/v2-g3'),{recursive:true});await preview.scrollIntoViewIfNeeded();await page.screenshot({path:path.resolve(__dirname,'../../var/v2-g3/practice-change-mock.png'),fullPage:true});await preview.getByRole('button',{name:'取消这次调整',exact:true}).click();
 invalid=true;await page.getByRole('button',{name:'生成实践调整预览',exact:true}).click();await page.getByText(/仓库地址无效/).waitFor();await page.getByLabel('仓库地址（可选）').fill('https://example.com/fixed');assert.equal(await page.getByRole('button',{name:'生成实践调整预览',exact:true}).isEnabled(),true);assert.equal(await page.getByRole('button',{name:'重试原预览',exact:true}).count(),0);
 assert.equal(modelCalls,0);assert.equal(await page.evaluate(()=>JSON.stringify(localStorage).includes('旧路线未保存方案')),false);
 // A valid published plan can have no practice project yet. Fresh mounting must
 // explain the empty context rather than dereference practice_projects[0].
 context={...context,practice_projects:[],tasks:[]};workspace={...workspace,stages:[{...workspace.stages[0],tasks:[]}]};
 page.on('dialog',d=>d.accept());await page.reload();await page.getByText('调整主项目与阶段任务',{exact:true}).click();
 await page.getByText('当前路线没有关联的主项目，请先在路线中安排实践项目与任务。',{exact:true}).waitFor();
 assert.equal(await page.getByLabel('主项目标题',{exact:true}).count(),0);
 console.log('PASS: custom/update/add knowledge roles, exact preview/confirm/cancel retries, 409 local input, explicit publish, visible old dirty original recovery; no model dispatch');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
