const {chromium}=require('playwright-core');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(5000);
 const stages=['a','b'].map((id,i)=>({stage:{stage_id:id,stable_key:'stage.'+id,title:i?'状态与恢复':'工具调用与结构化输出',section_kind:'core',order_index:i,objective:'检查可运行结果'},nodes:[{node_id:'n'+id,title:'节点 '+id,objectives:['理解与实现'],prerequisite_ids:[],child_ids:[],progress:null,source_status:'verified'}],units:[{unit_id:'u'+id,title:'单元 '+id,node_ids:['n'+id],progress:i?'skipped':'completed',progress_recorded:true}],tasks:[{task_id:'t'+id,title:'任务 '+id,goal:'验证工具结果',acceptance:['检查失败情况'],in_scope:[],out_scope:[],knowledge_links:[],status:'planned'}],resources:[]}));
 stages.forEach(s=>s.tasks.push({...s.tasks[0],task_id:s.tasks[0].task_id+'2',title:s.tasks[0].title+' 第二项'}));
 const workspace={plan:{plan_id:'p',revision:1,goal_snapshot:'学习 Agent',project_id:'project',stages:stages.map(s=>s.stage),unit_links:[],task_links:[],stage_resources:[],extensions:[]},stages,total_units:2,completed_units:1};
 let summaryReads=[];
 await page.route('**/api/v1/**',r=>r.abort('blockedbyclient'));
 await page.route('**/api/v1/session',r=>r.fulfill({json:{username:'设计测试',project_ids:['project'],csrf_token:'test'}}));
 await page.route('**/api/v1/workspace?**',r=>r.fulfill({json:workspace}));
 await page.route('**/healthz',r=>r.fulfill({json:{fake_llm:true}}));
 await page.route('**/api/v1/summaries?**',r=>{const url=new URL(r.request().url());assert.equal(url.searchParams.has('unit_id'),false);summaryReads.push(url.searchParams.get('stage_id'));return r.fulfill({json:{project_id:'project',plan_id:'p',stage_id:url.searchParams.get('stage_id'),unit_id:null,version:0,questions:['这个阶段如何解释？'],attempts:[],history_truncated:false}});});
 await page.route('**/api/v1/prompts?**',r=>{const url=new URL(r.request().url()),id=url.searchParams.get('stage_id'),taskId=url.searchParams.get('task_id');return r.fulfill({json:{project_id:'project',plan_id:'p',stage_id:id,task_id:taskId,version:0,practice_project:{practice_project_id:'practice',title:'当前主项目',idea:'练习工具',version:1,status:'planned'},task:stages.find(s=>s.stage.stage_id===id).tasks.find(t=>t.task_id===taskId),revisions:[],history_truncated:false}});});
 await page.goto((process.env.STUDYPLAN_URL||'http://127.0.0.1:5177')+'/#workspace');
 const triggers=page.locator('.stage-trigger');await triggers.first().waitFor();assert.deepEqual(await triggers.evaluateAll(buttons=>buttons.map(b=>b.getAttribute('aria-expanded'))),['false','false']);
 await triggers.first().click();assert.equal(await triggers.first().getAttribute('aria-expanded'),'true');assert.equal(await page.locator('#stage-children-a').isVisible(),true);assert.equal(await page.locator('#stage-children-b').isVisible(),false);
 const before=await triggers.nth(1).boundingBox();await triggers.first().click();const after=await triggers.nth(1).boundingBox();assert.ok(before.y>after.y,'expanded nodes push later stages down');
 await page.getByRole('navigation',{name:'全局导航'}).getByRole('button',{name:'项目实践',exact:true}).click();
 const prompt=page.getByRole('textbox',{name:'方案与 Prompt 原文',exact:true});await prompt.waitFor();await prompt.fill('工具阶段的未保存方案');
 await triggers.nth(1).click();assert.equal(await page.getByRole('combobox',{name:'实践所属阶段'}).inputValue(),'b');assert.ok(page.url().endsWith('#practice'));await prompt.fill('恢复阶段的未保存方案');
 await page.getByRole('combobox',{name:'实践所属阶段'}).selectOption('a');assert.equal(await triggers.first().getAttribute('aria-current'),'step');assert.equal(await prompt.inputValue(),'工具阶段的未保存方案');
 await page.locator('#stage-children-b').getByRole('button',{name:'整理阶段总结 →',exact:true}).click();assert.equal(await page.getByRole('combobox',{name:'总结所属阶段'}).inputValue(),'b');await page.getByRole('combobox',{name:'总结所属阶段'}).selectOption('a'); await page.getByRole('navigation',{name:'全局导航'}).getByRole('button',{name:'阶段总结',exact:true}).click();const summary=page.getByRole('textbox',{name:'总结原文',exact:true});await summary.waitFor();await summary.fill('工具阶段的未保存总结');
 await triggers.nth(1).click();assert.equal(await page.getByRole('combobox',{name:'总结所属阶段'}).inputValue(),'b');assert.ok(page.url().endsWith('#summary'));await summary.fill('恢复阶段的未保存总结');
 await page.getByRole('combobox',{name:'总结所属阶段'}).selectOption('a');assert.equal(await summary.inputValue(),'工具阶段的未保存总结');assert.equal(await triggers.first().getAttribute('aria-current'),'step');
 await page.getByRole('navigation',{name:'全局导航'}).getByRole('button',{name:'项目实践',exact:true}).click();assert.equal(await prompt.inputValue(),'工具阶段的未保存方案');
 if(await triggers.nth(1).getAttribute('aria-expanded')!=='true')await triggers.nth(1).click();
 await page.locator('#stage-children-b').getByRole('button',{name:'任务 b 第二项 →',exact:true}).click();
 const taskSelect=page.getByRole('combobox',{name:'实践任务',exact:true});await page.waitForFunction(()=>document.querySelector('select[aria-label="实践任务"]').value==='tb2');assert.equal(await taskSelect.inputValue(),'tb2');await prompt.fill('第二项任务独立原文');
 await taskSelect.selectOption('tb');assert.equal(await prompt.inputValue(),'恢复阶段的未保存方案');await taskSelect.selectOption('tb2');assert.equal(await prompt.inputValue(),'第二项任务独立原文');
 await taskSelect.selectOption('tb');await page.getByRole('navigation',{name:'全局导航'}).getByRole('button',{name:'阶段总结',exact:true}).click();await page.getByRole('navigation',{name:'全局导航'}).getByRole('button',{name:'项目实践',exact:true}).click();assert.equal(await taskSelect.inputValue(),'tb','ordinary rerender must not reapply old task intent');
 assert.ok(summaryReads.includes('a')&&summaryReads.includes('b'));assert.equal(await page.getByRole('combobox',{name:'总结所属学习单元'}).count(),0);
 console.log('PASS: collapsed accordion, in-flow expansion, bidirectional practice/summary stage sync, unsaved buffers, specific second-task navigation and stage-only summary target');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
