const {chromium}=require('playwright-core');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1366,height:900}});page.setDefaultTimeout(5000);
 const stage={stage_id:'s',stable_key:'stage.test',title:'资料测试阶段',section_kind:'core',order_index:0,objective:'整理资料与成果'};
 const nodes=[{node_id:'n',title:'知识标题',objectives:['说明概念'],prerequisite_ids:[],child_ids:[],progress:'completed',source_status:'verified'}];
 const units=['u1','u2'].map(id=>({unit_id:id,title:'资料单元 '+id,node_ids:['n'],objectives:[],progress:'completed',progress_recorded:true}));
 const workspace={plan:{plan_id:'p',project_id:'project',revision:1,goal_snapshot:'资料操作',stages:[stage],unit_links:[],task_links:[],stage_resources:[],extensions:[]},stages:[{stage,nodes,units,tasks:[],resources:[],completion:{status:'incomplete',summary_completed:false,completed_practice_tasks:0,total_practice_tasks:0}}],completed_stages:0,total_stages:1,completed_units:999,total_units:999};
 const primary={assignment_id:'primary',source_ref:'source',source_version:1,section_refs:['intro'],role:'primary',node_ids:[],title:'受控课程',creator:'Fixture',language:'zh',documentation_version:null,verification_status:'reviewed',ordered_sections:[{section_id:'intro',title:'入门章节',url:'https://example.invalid/intro',order_index:0}],warnings:[]};
 workspace.plan.stage_resources=[primary];workspace.stages[0].resources=[primary];
 let saves=0,failWorkspaceRefresh=false;
 await page.route('**/api/v1/**',r=>r.abort('blockedbyclient'));
 await page.route('**/api/v1/session',r=>r.fulfill({json:{username:'资料用户',project_ids:['project'],csrf_token:'test'}}));
 await page.route('**/healthz',r=>r.fulfill({json:{fake_llm:true}}));
 await page.route('**/api/v1/workspace?**',r=>failWorkspaceRefresh?r.abort('failed'):r.fulfill({json:workspace}));
 await page.route('**/api/v1/resource-changes/catalog?**',r=>r.fulfill({json:[]}));
 await page.route('**/api/v1/resources/selections?**',r=>r.fulfill({json:[]}));
 await page.route('**/api/v1/preferences?**',r=>r.fulfill({json:{project:null,unit:null,node:null,effective:{scope:'system',scope_ref:'system',mode:'mixed',language:'zh',official_priority:true,pace:'normal',version:1},inherited:true,versions:{project:0,unit:0,node:0},invalid_scopes:[]}}));
 await page.route('**/api/v1/summaries?**',r=>{if(r.request().method()==='GET')return r.fulfill({json:{project_id:'project',plan_id:'p',stage_id:'s',unit_id:null,version:0,questions:[],attempts:[]}});saves++;const body=r.request().postDataJSON();const attempt={...body,attempt_id:'a'+saves,project_id:'project',unit_id:null,attempt_no:saves,version:saves,content_hash:'test',created_at:new Date().toISOString(),rubric_snapshot:{stage_title:stage.title},review:null,run_id:null,run_status:null};workspace.stages[0].completion.status='completed';workspace.completed_stages=1;return r.fulfill({json:{attempt,thread:{project_id:'project',plan_id:'p',stage_id:'s',unit_id:null,version:saves,questions:[],attempts:[attempt]}}});});
 await page.goto((process.env.STUDYPLAN_URL||'http://127.0.0.1:5177')+'/#workspace');
 await page.getByRole('heading',{name:stage.title,exact:true}).waitFor();assert.match(await page.locator('.course-top').innerText(),/0\/1 阶段完成/);assert.equal(await page.locator('.stage-completion').innerText(),'未完成');
 assert.equal(await page.getByRole('combobox',{name:'本次出现位置进度'}).count(),0);assert.equal(await page.getByRole('combobox',{name:'资料所属学习单元'}).count(),0);
 await page.locator('.stage-trigger').click();assert.equal(await page.locator('.node-button small').count(),0);
 await page.getByRole('button',{name:'资料偏好',exact:true}).click();let dialog=page.getByRole('dialog',{name:'资料偏好',exact:true});await dialog.waitFor();assert.equal(await page.getByRole('dialog').count(),1);
 await dialog.getByRole('textbox',{name:'资料语言',exact:true}).fill('ja');await dialog.getByRole('combobox',{name:'资料所属学习单元'}).selectOption('u2');await dialog.getByRole('textbox',{name:'资料语言',exact:true}).fill('fr');
 await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>document.activeElement.textContent),'资料偏好');
 await page.getByRole('button',{name:'资料偏好',exact:true}).click();assert.equal(await dialog.getByRole('textbox',{name:'资料语言',exact:true}).inputValue(),'fr');await dialog.getByRole('button',{name:'关闭资料偏好',exact:true}).click();
 await page.getByRole('button',{name:'补充本单元资料',exact:true}).click();dialog=page.getByRole('dialog',{name:'补充本单元资料',exact:true});await dialog.waitFor();assert.equal(await dialog.getByRole('combobox',{name:'资料所属学习单元'}).inputValue(),'u2');await dialog.getByRole('textbox',{name:'搜索词',exact:true}).fill('保留的本地搜索词');await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});
 await page.getByRole('button',{name:'补充本单元资料',exact:true}).click();assert.equal(await dialog.getByRole('textbox',{name:'搜索词',exact:true}).inputValue(),'保留的本地搜索词');await dialog.getByRole('combobox',{name:'资料所属学习单元'}).selectOption('u1');assert.equal(await dialog.getByRole('textbox',{name:'搜索词',exact:true}).inputValue(),'');await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'替换本阶段主线',exact:true}).click();dialog=page.getByRole('dialog',{name:'替换本阶段主线',exact:true});await dialog.waitFor();await dialog.getByRole('combobox',{name:'私人资料沿用策略'}).selectOption('copy_active');await page.keyboard.press('Escape');await page.getByRole('button',{name:'替换本阶段主线',exact:true}).click();assert.equal(await dialog.getByRole('combobox',{name:'私人资料沿用策略'}).inputValue(),'copy_active');
 await page.setViewportSize({width:390,height:844});const bounds=await dialog.boundingBox();assert.ok(bounds.width<=390&&bounds.x>=0);await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>Boolean(document.activeElement.closest('dialog[open]'))),true);await page.keyboard.press('Escape');await page.setViewportSize({width:1366,height:900});
 await page.getByRole('navigation',{name:'全局导航'}).getByRole('button',{name:'阶段总结',exact:true}).click();const editor=page.getByRole('textbox',{name:'总结原文',exact:true});await editor.waitFor();await editor.fill('阶段总结原文');await page.getByRole('button',{name:'保存总结',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.course-top').textContent.includes('1/1 阶段完成'));assert.equal(saves,1);
 failWorkspaceRefresh=true;await editor.fill('第二次阶段总结原文');await page.getByRole('button',{name:'保存总结',exact:true}).click();await page.getByText('总结已保存，阶段状态暂未刷新。可稍后重新加载学习空间。',{exact:true}).waitFor();assert.equal(saves,2);assert.equal(await page.getByRole('button',{name:'重试原保存',exact:true}).count(),0);
 console.log('PASS: independent native dialogs, focus/ESC, closed-state local buffers, shared unit isolation, 390px bounds, server completion and successful save refresh isolation');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
