const {chromium}=require('playwright-core');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage();
 await page.route('**/api/v1/**',r=>r.abort('blockedbyclient'));
 const stage={stage_id:'s1',stable_key:'stage.test',title:'测试阶段',section_kind:'core',order_index:0,objective:'测试学习'};
 const units=['u1','u2'].map((unit_id,i)=>({unit_id,stable_key:'unit.'+i,title:'单元'+(i+1),objectives:[],rubric_version:1,progress:'not_started',node_ids:[],progress_recorded:false}));
 const workspace={plan:{plan_id:'p1',project_id:'project',revision:1,goal_snapshot:'学习目标',stages:[stage],unit_links:[],task_links:[],stage_resources:[],extensions:[]},stages:[{stage,nodes:[],units,resources:[],tasks:[]}],total_units:2,completed_units:0};
 let posts=[];const lists={u1:[],u2:[]};let reads=0,missing=false,manualFails=false,slow=false,releaseSlow,signalSlow;
 const candidate={resource_id:'c1',project_id:'project',url:'https://example.org/docs',title:'候选文档',media_type:'text',language:'en',provenance:'community',verification_status:'unverified',checked_at:null,source_note:'Tavily search result'};
 const search={search_id:'search1',status:'succeeded',query:'工具教程',candidates:[candidate],error:null,created_at:new Date().toISOString()};
 await page.route('**/api/v1/session',r=>r.fulfill({json:{username:'测试用户',project_ids:['project'],csrf_token:'test'}}));
 await page.route('**/api/v1/workspace?**',r=>r.fulfill({json:workspace}));
 await page.route('**/healthz',r=>r.fulfill({json:{llm_provider:'fake'}}));
 await page.route('**/api/v1/exposures**',r=>r.fulfill({json:r.request().url().includes('/history')?[]:units.map(u=>({exposure_id:'ex-'+u.unit_id,project_id:'project',plan_id:'p1',stage_id:'s1',unit_id:u.unit_id,status:'not_started',version:0,recorded:false,node_snapshot:[],source_snapshot:{kind:'assigned_source_bindings',public_assignments:[],private_selections:[]},updated_at:null}))}));
 await page.route('**/api/v1/preferences?**',r=>r.fulfill({json:{project:null,unit:null,node:null,effective:{scope:'system',scope_ref:'system',mode:'mixed',language:'zh',official_priority:true,pace:'normal',version:1},inherited:true,versions:{project:0,unit:0,node:0},invalid_scopes:[]}}));
 await page.route('**/api/v1/resources/**',async r=>{const req=r.request(),url=new URL(req.url()),body=req.postDataJSON();const unit=url.searchParams.get('unit_id')||body?.unit_id;
 if(url.pathname.endsWith('/searches')){posts.push(body);if(posts.length===1)return r.abort('failed');if(slow){signalSlow();await new Promise(resolve=>{releaseSlow=resolve;});}return r.fulfill({json:search});}
 if(url.pathname.includes('/searches/')){reads++;if(missing)return r.fulfill({status:404,json:{message:'原查询尚未保存'}});return r.fulfill({json:search});}
 if(req.method()==='GET')return r.fulfill({json:lists[unit]});
 if(req.method()==='DELETE'){lists[unit]=[];return r.fulfill({json:{removed:true}});}
 if(url.pathname.endsWith('/manual')&&manualFails)return r.fulfill({status:503,json:{message:'保存暂时不可用'}});
 const resource=url.pathname.endsWith('/manual')?{...candidate,resource_id:'manual',title:body.title,url:body.url,provenance:'user_provided',source_note:'用户手动接入'}:candidate;
 lists[unit]=[{selection_id:'selection1',resource,created_at:new Date().toISOString()}];return r.fulfill({json:lists[unit][0]});});
 await page.goto((process.env.STUDYPLAN_URL||'http://127.0.0.1:5174')+'/#workspace');
 await page.getByRole('button',{name:'补充本单元资料',exact:true}).click();
 await page.getByRole('dialog',{name:'补充本单元资料',exact:true}).getByLabel('资料所属学习单元').waitFor({timeout:2000});
 await page.getByLabel('搜索词').fill('工具教程');
 assert.equal(posts.length,0);
 await page.getByRole('button',{name:'搜索资料',exact:true}).click();
 await page.getByRole('button',{name:'读取原查询',exact:true}).click();
 await page.getByRole('button',{name:'选用此资料'}).click();
 await page.getByRole('heading',{name:'已选资料'}).waitFor();
 assert.equal(posts.length,1);assert.ok(posts[0].idempotency_key);assert.equal(reads,1);
 await page.reload();await page.getByRole('button',{name:'补充本单元资料',exact:true}).click();await page.getByRole('button',{name:'移除此资料'}).waitFor();
 assert.match(await page.locator('[aria-label="单元资料选取"]').innerText(),/未核验/);
 await page.getByRole('dialog',{name:'补充本单元资料',exact:true}).getByLabel('资料所属学习单元').selectOption('u2');
 missing=true;
 await page.getByLabel('搜索词').fill('新的搜索词');
 await page.getByRole('button',{name:'搜索资料',exact:true}).click();
 await page.getByRole('button',{name:'读取原查询',exact:true}).click();
 await page.getByRole('button',{name:'提交原查询',exact:true}).waitFor();
 assert.equal(posts.length,2);assert.notEqual(posts[0].idempotency_key,posts[1].idempotency_key);
 await page.getByRole('button',{name:'提交原查询',exact:true}).click();
 assert.equal(posts.length,3);assert.equal(posts[1].idempotency_key,posts[2].idempotency_key);assert.equal(posts[1].query,posts[2].query);
 await page.getByLabel('资料标题').fill('手动GitHub候选');await page.getByLabel('资料网址').fill('https://github.com/example/repository');
 manualFails=true;
 await page.getByRole('button',{name:'保存手动资料'}).click();await page.locator('[aria-label="单元资料选取"]').getByRole('alert').waitFor();
 assert.equal(await page.getByLabel('资料标题').inputValue(),'手动GitHub候选');assert.equal(await page.getByLabel('资料网址').inputValue(),'https://github.com/example/repository');
 manualFails=false;
 await page.getByRole('button',{name:'保存手动资料'}).click();await page.getByRole('link',{name:'手动GitHub候选'}).waitFor();
 await page.screenshot({path:require('node:path').resolve(__dirname,'../../var/v2-g2/resource-picker-mock.png'),fullPage:true});
 assert.equal(lists.u1.length,1);assert.equal(lists.u2.length,1);
 await page.getByRole('button',{name:'移除此资料'}).click();await page.getByText('本单元还没有选取资料。',{exact:true}).waitFor();
 await page.getByRole('dialog',{name:'补充本单元资料',exact:true}).getByLabel('资料所属学习单元').selectOption('u1');
 await page.getByLabel('搜索词').fill('旧单元慢查询');slow=true;
 const slowEntered=new Promise(resolve=>{signalSlow=resolve;});
 await page.getByRole('button',{name:'搜索资料',exact:true}).click();await slowEntered;
 await page.getByRole('dialog',{name:'补充本单元资料',exact:true}).getByLabel('资料所属学习单元').selectOption('u2');
 releaseSlow();await page.getByRole('button',{name:'重新搜索',exact:true}).waitFor();
 assert.equal(await page.getByLabel('搜索词').inputValue(),'新的搜索词');
 assert.doesNotMatch(await page.locator('[aria-label="单元资料选取"]').innerText(),/旧单元慢查询/);
 console.log('PASS: explicit search, read-only/key recovery, selection refresh, unit scope, stale response and manual failure/remove');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
