const {chromium}=require('playwright-core');
const assert=require('node:assert/strict');
// Breaks caught: sparse chapter gaps, implicit publish/copy policy, lost exact
// commands on network ambiguity, autoload POST, and stale workspace publication.
const consoleErrors=[],pageErrors=[],unknown=[];
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});
try{const page=await browser.newPage();page.setDefaultTimeout(8000);
page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});page.on('pageerror',e=>pageErrors.push(e.message));
await page.route('**/api/v1/**',r=>{unknown.push(r.request().method()+' '+new URL(r.request().url()).pathname);return r.abort('blockedbyclient');});
const sections=['a','b','c'].map((section_id,i)=>({section_id,title:['第一章','第二章','第三章'][i],url:'https://example.invalid/chapter/'+section_id,order_index:[10,30,90][i],source_id:'new-source',source_version:4}));
const source={source_id:'new-source',source_version:4,title:'替代课程',creator:'测试作者',language:'zh',documentation_version:'2026',canonical_url:'https://example.invalid/course',verification_status:'reviewed'};
const roles=['primary','supplement','comparison','reference','case_study','practice'];
function workspace(revision){const stage_id=revision===1?'s1':'s2',unit_id=revision===1?'u1':'u2';const stage={stage_id,stable_key:'stage',title:revision===1?'原阶段':'新阶段',section_kind:'core',order_index:0,objective:'路线目标'};
const node={node_id:'n1',stable_key:'node',title:'知识点',node_type:'concept',source_status:'ai_draft',objectives:[],prerequisite_ids:[],child_ids:[],progress:null};
const resources=roles.map((role,i)=>({assignment_id:'assignment'+i,source_ref:revision===1?'old-source':'new-source',source_version:revision===1?2:4,section_refs:revision===1?['old']:['a','b','c'],role,node_ids:[],title:role+'资料',creator:'测试来源',language:'zh',documentation_version:'2026',verification_status:'reviewed',ordered_sections:revision===1?[{section_id:'old'+i,title:role+'原章节',url:'https://example.invalid/old/'+i,order_index:10}]:sections,warnings:[]}));
return {plan:{plan_id:'p'+revision,project_id:'project',revision,goal_snapshot:'目标',stages:[stage],unit_links:[],task_links:[],stage_resources:resources,extensions:[]},stages:[{stage,nodes:[node],units:[{unit_id,stable_key:'unit',title:'学习单元',objectives:[],rubric_version:1,progress:revision===1?'completed':'not_started',node_ids:['n1'],progress_recorded:revision===1}],resources,tasks:[]}],total_units:1,completed_units:revision===1?1:0};}
let revision=1,abortPreview=true,abortDecision=false,decisionConflict=false;const previews=new Map(),previewCommands=[],decisionCommands=[],getIds=[],workspaceReads=[];
function preview(id,body){return {proposal_id:id,draft_id:'draft'+id,project_id:'project',actor_id:'actor',base_plan_id:'p1',base_revision:1,status:'pending',preview_hash:'hash-'+id,copy_policy:body.copy_policy,before:{source:{...source,title:'原课程'},source_version:2,sections:[{section_id:'old',title:'旧章节',url:'https://example.invalid/old'}]},after:{source,source_version:4,sections},impact:{unit_ids:['u1'],nodes:[{node_id:'n1',title:'知识点',stable_key:'node',content_version:1}],prerequisites:[],prerequisite_status:'recorded_relations_only',coverage:{mapping_status:'missing',mapped_node_keys:[],unmatched_node_ids:['n1'],required_extension_topics:['必要补缺主题']},workload:{before_section_count:1,after_section_count:3},progress:{started_units:1,completed_units:1,skipped_units:0,observations:[]},private_bindings:{copy_count:2,active_count:2,history_retained:true,policy:body.copy_policy}},warnings:['仍需核对适用性'],created_at:'2026-10-01T00:00:00Z',draft_hash:'draft-hash',catalog_digest:'catalog'};}
await page.route('**/api/v1/session',r=>r.fulfill({json:{username:'Mock用户',project_ids:['project'],csrf_token:'mock'}}));
await page.route('**/healthz',r=>r.fulfill({json:{fake_llm:true}}));
await page.route('**/api/v1/workspace?**',r=>{workspaceReads.push(revision);return r.fulfill({json:workspace(revision)});});
await page.route('**/api/v1/resources/**',r=>{assert.equal(r.request().method(),'GET');return r.fulfill({json:[]});});
await page.route('**/api/v1/exposures**',r=>{assert.equal(r.request().method(),'GET');const url=new URL(r.request().url());return r.fulfill({json:url.pathname.endsWith('/history')?[]:[{exposure_id:'ex',project_id:'project',plan_id:'p'+revision,stage_id:revision===1?'s1':'s2',unit_id:revision===1?'u1':'u2',status:revision===1?'completed':'not_started',version:revision===1?1:0,recorded:revision===1,node_snapshot:[],source_snapshot:{public_assignments:[],private_selections:[]},updated_at:null}]});});
await page.route('**/api/v1/preferences?**',r=>{assert.equal(r.request().method(),'GET');return r.fulfill({json:{project:null,unit:null,node:null,effective:{scope:'system',scope_ref:'system',mode:'mixed',language:'zh',official_priority:true,pace:'normal',version:1},inherited:true,versions:{project:0,unit:0,node:0},invalid_scopes:[]}});});
await page.route('**/api/v1/resource-changes**',r=>{const req=r.request(),path=new URL(req.url()).pathname;
if(req.method()==='GET'){if(path.endsWith('/catalog'))return r.fulfill({json:[{source,sections,index_truncated:false}]});const id=path.split('/').at(-1);getIds.push(id);assert.ok(previews.has(id));return r.fulfill({json:previews.get(id)});}
const body=req.postDataJSON();assert.equal(req.method(),'POST');
if(path.endsWith('/resource-changes')){previewCommands.push(body);let value=[...previews.values()].find(p=>p.key===body.idempotency_key);if(!value){value={...preview('proposal'+(previews.size+1),body),key:body.idempotency_key};if(previews.size)value.warnings=[];previews.set(value.proposal_id,value);}if(abortPreview){abortPreview=false;return r.abort('failed');}return r.fulfill({json:value});}
const [,id,action]=path.match(/resource-changes\/([^/]+)\/(confirm|cancel)$/);decisionCommands.push({id,action,body});const value=previews.get(id);assert.ok(value);if(decisionConflict){decisionConflict=false;return r.fulfill({status:409,json:{message:'当前路线版本变化，请读取原预览'}});}assert.equal(body.preview_hash,value.preview_hash);assert.equal(body.expected_version,1);
if(action==='confirm'){assert.equal(body.acknowledge_warnings,true);revision=2;value.status='confirmed';}else value.status='cancelled';
if(abortDecision){abortDecision=false;return r.abort('failed');}return r.fulfill({json:{proposal_id:id,action,status:value.status,plan_id:action==='confirm'?'p2':null,revision:action==='confirm'?2:null,created:true,copied_selections:action==='confirm'?2:0}});});
const url=(process.env.STUDYPLAN_URL||'http://127.0.0.1:5174')+'/#workspace';await page.goto(url);
const panel=page.getByRole('region',{name:'主线资料替换'});
await panel.getByRole('heading',{name:'替换本阶段主线'}).waitFor();
for(const label of ['主线','补充','可选对照','参考','案例','实践'])assert.ok(await page.locator('.resource-group .pill').filter({hasText:label}).count(),label+' role displayed');
assert.equal(previewCommands.length,0);assert.equal(decisionCommands.length,0);
async function choose(){await page.getByLabel('公开资料目录').selectOption('new-source');await page.getByLabel('起始章节').selectOption('a');await page.getByLabel('结束章节').selectOption('c');}
await choose();assert.equal(await panel.getByRole('button',{name:'查看主线替换差异'}).isDisabled(),true,'explicit copy policy required');await page.getByLabel('私人资料沿用策略').selectOption('copy_active');
await panel.getByRole('button',{name:'查看主线替换差异'}).click();await panel.getByRole('button',{name:'重试原主线操作'}).waitFor();assert.equal(previewCommands.length,1);assert.deepEqual(previewCommands[0].section_refs,['a','b','c'],'sparse indices must still include middle chapter');assert.equal(previewCommands[0].assignment_id,'assignment0');assert.equal(previewCommands[0].source_version,4);
await panel.getByRole('button',{name:'重试原主线操作'}).click();await panel.getByText('预览状态：待确认',{exact:true}).waitFor();assert.deepEqual(previewCommands[0],previewCommands[1]);assert.equal(decisionCommands.length,0,'preview alone cannot confirm');
assert.match(await panel.innerText(),/原课程/);assert.match(await panel.innerText(),/替代课程/);assert.match(await panel.innerText(),/必要补缺主题/);assert.match(await panel.innerText(),/仍需核对适用性/);assert.match(await panel.innerText(),/1 → 3/);assert.equal(await panel.getByRole('button',{name:'确认发布新路线'}).isDisabled(),true);
const beforeReload=previewCommands.length;await page.reload();await panel.getByText('预览状态：待确认',{exact:true}).waitFor();assert.equal(previewCommands.length,beforeReload,'reload must GET retained preview without POST');assert.ok(getIds.includes('proposal1'));assert.equal(decisionCommands.length,0);
await panel.getByRole('button',{name:'取消主线预览'}).click();await panel.getByText('预览状态：已取消',{exact:true}).waitFor();assert.equal(revision,1);assert.equal(await page.getByRole('heading',{name:'原阶段',exact:true}).count(),1);assert.equal(await page.evaluate(()=>localStorage.getItem('studyplan:resource-change:project:p1:s1')),null);
await choose();await page.getByLabel('私人资料沿用策略').selectOption('keep_history_only');await panel.getByRole('button',{name:'查看主线替换差异'}).click();await panel.getByText('预览状态：待确认',{exact:true}).waitFor();assert.equal(previewCommands.at(-1).copy_policy,'keep_history_only');assert.notEqual(previewCommands.at(-1).idempotency_key,previewCommands[0].idempotency_key);assert.equal(await panel.getByRole('button',{name:'确认发布新路线'}).isDisabled(),true,'explicit checkbox is required even when warning list is empty');
decisionConflict=true;await panel.getByRole('checkbox').check();await panel.getByRole('button',{name:'确认发布新路线'}).click();await panel.getByRole('alert').waitFor();assert.equal(await page.getByLabel('私人资料沿用策略').inputValue(),'keep_history_only');assert.match(await panel.innerText(),/预览状态：待确认/);assert.equal(await page.getByRole('heading',{name:'原阶段',exact:true}).count(),1);const readCount=getIds.length;
await panel.getByRole('button',{name:'读取原主线预览'}).click();await panel.getByRole('alert').waitFor({state:'hidden'});assert.equal(getIds.length,readCount+1);assert.equal(await panel.getByRole('checkbox').isChecked(),false);
abortDecision=true;await panel.getByRole('checkbox').check();await panel.getByRole('button',{name:'确认发布新路线'}).click();await panel.getByRole('button',{name:'重试原主线操作'}).waitFor();assert.equal(await page.getByRole('heading',{name:'原阶段',exact:true}).count(),1,'ambiguous result must not replace workspace');await panel.getByRole('button',{name:'重试原主线操作'}).click();await page.getByRole('heading',{name:'新阶段',exact:true}).waitFor();assert.deepEqual(decisionCommands.at(-1),decisionCommands.at(-2),'retry original decision body/key');assert.equal(workspaceReads.at(-1),2);await page.getByRole('region',{name:'出现位置学习进度'}).getByText('当前记录：未开始',{exact:true}).waitFor();assert.equal(await page.getByLabel('进度动作').inputValue(),'not_started');assert.equal(await page.evaluate(()=>localStorage.getItem('studyplan:resource-change:project:p1:s1')),null);
assert.deepEqual(unknown,[],'all API calls mocked');assert.deepEqual(pageErrors,[],'no application exceptions');assert.deepEqual(consoleErrors.filter(message=>!/^Failed to load resource: (net::ERR_FAILED|the server responded with a status of 409 \(Conflict\))$/.test(message)),[],'no unexpected browser console errors');
await page.screenshot({path:require('node:path').resolve(__dirname,'../../var/v2-g2/resource-changes-mock.png'),fullPage:true});
console.log('PASS: six roles, contiguous sparse chapters, explicit policy/ack, preview-only, exact preview/decision retries, conflict reread, cancel, GET-only reload, published plan2/new stage/not_started');
console.log('Browser console errors (expected mocked network aborts only):',JSON.stringify(consoleErrors));
}finally{await browser.close();}})().catch(e=>{console.error(e);console.log('Browser console errors:',JSON.stringify(consoleErrors));console.log('Page errors:',JSON.stringify(pageErrors));process.exitCode=1;});
