const {chromium}=require('playwright-core');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage();page.setDefaultTimeout(4000);
 const stage={stage_id:'s',stable_key:'stage.tools',title:'工具阶段',order_index:0,section_kind:'core',objective:'工具'};
 const task={task_id:'t',practice_project_id:'pp',stable_key:'task.tools',title:'交付助手',goal:'实现工具调用',in_scope:['工具协议'],out_scope:['公网部署'],acceptance:['成功结果可解释','错误有明确处理'],status:'pending',version:1,knowledge_links:[{node_id:'n',stable_key:'tools',title:'工具调用',content_version:1,role:'core'}]};
 const practice={practice_project_id:'pp',title:'我的助手',idea:'构建可检查的工具助手',repo_url:null,status:'idea',version:1};
 let workspace={plan:{plan_id:'p',project_id:'project',revision:1,goal_snapshot:'学习目标',stages:[stage],unit_links:[],task_links:[],stage_resources:[],extensions:[]},stages:[{stage,nodes:[],units:[],resources:[],tasks:[task,{...task,task_id:'t-alt',title:'另一个任务'}]}],total_units:0,completed_units:0};
 const thread={project_id:'project',plan_id:'p',stage_id:'s',task_id:'t',plan_version:1,version:0,task_version:1,practice_project:practice,task,submissions:[],history_truncated:false,platform_execution_available:false,source_check_available:false};
 const submissions={},saves=[],decisions=[],decisionReceipts={};let failSave=true,failDecision=true,dropSave=false,conflict=false,invalid=false,late=false,releaseRead,enteredRead,holdSave=false,releaseSave,enteredSave,unexpected=0;
 const kinds=['project_description','evaluation','architecture','design_decision','failure_review','explanation','other'];
 const legacy={submission_id:'legacy',project_id:'project',plan_id:null,stage_id:null,task_id:'old-task',submission_no:0,version:0,note:'  旧成果原文  ',repo_url:null,evidence:[],legacy_evidence:['旧报告未结构化原文'],artifact_kind:'other',parent_submission_id:null,content_hash:'old',task_snapshot:{snapshot_status:'legacy_unfrozen',plan_id:null,plan_revision:null,stage_id:null,stage_title:null,practice_project:null,task:null,warning:'旧成果缺少当时要求，不能补写当前任务'},evidence_grade:'verified',verification_available:false,source_check_available:false,review:null,created_at:new Date().toISOString()};
 submissions.legacy=legacy;
 await page.addInitScript(()=>{navigator.clipboard.writeText=async text=>{window.submissionCopied=text;};});
 await page.route('**/api/v1/**',r=>{unexpected++;return r.abort('blockedbyclient');});
 await page.route('**/api/v1/session',r=>r.fulfill({json:{username:'成果用户',project_ids:['project'],csrf_token:'test-csrf'}}));
 await page.route('**/healthz',r=>r.fulfill({json:{llm_provider:'fake'}}));
 await page.route('**/api/v1/workspace?**',r=>r.fulfill({json:workspace}));
 await page.route('**/api/v1/prompts**',r=>r.fulfill({json:{project_id:'project',plan_id:workspace.plan.plan_id,stage_id:'s',task_id:workspace.stages[0].tasks[0].task_id,version:0,practice_project:practice,task:workspace.stages[0].tasks[0],revisions:[],history_truncated:false}}));
 await page.route('**/api/v1/outcomes?**',r=>{const more=new URL(r.request().url()).searchParams.has('cursor');return r.fulfill({json:{project_id:'project',groups:kinds.map(kind=>({kind,title:kind,total_records:['architecture','other'].includes(kind)?1:0,items:kind==='architecture'&&!more?[{submission_id:'sub1',artifact_kind:kind,plan_revision:1,stage_title:stage.title,task_title:task.title,project_title:practice.title,evidence_grade:'reported',conclusion:'accepted',manual_confirmation:true,created_at:new Date().toISOString()}]:kind==='other'&&more?[{submission_id:'legacy',artifact_kind:'other',plan_revision:null,stage_title:null,task_title:null,project_title:null,evidence_grade:'verified',conclusion:null,manual_confirmation:false,created_at:new Date().toISOString()}]:[]})),next_cursor:more?null:'older'}});});
 await page.route('**/api/v1/submissions**',async r=>{
  const req=r.request(),url=new URL(req.url());if(req.method()==='GET'){
   if(url.pathname.endsWith('/history'))return r.fulfill({json:{items:Object.values(submissions),next_cursor:null}});
   if(url.pathname!== '/api/v1/submissions')return r.fulfill({json:submissions[url.pathname.split('/').at(-1)]});
   const value=JSON.parse(JSON.stringify(url.searchParams.get('plan_id')==='p2'?{...thread,plan_id:'p2',task_id:'t2',plan_version:2,version:0,task_version:1,task:{...task,task_id:'t2',title:'新路线任务'},submissions:[]}:url.searchParams.get('task_id')==='t-alt'?{...thread,task_id:'t-alt',version:0,task:{...task,task_id:'t-alt',title:'另一个任务'},submissions:[]}:thread));if(late){late=false;enteredRead();await new Promise(resolve=>{releaseRead=resolve;});}return r.fulfill({json:value});
  }
  assert.equal(req.headers()['x-csrf-token'],'test-csrf');const body=req.postDataJSON();
  if(url.pathname.endsWith('/decision')){const id=url.pathname.split('/').at(-2);decisions.push({id,body});if(decisionReceipts[body.idempotency_key])return r.fulfill({json:decisionReceipts[body.idempotency_key]});const s=submissions[id];s.review={review_id:'review',submission_id:id,conclusion:body.conclusion,reviewer_kind:'user',rationale:body.rationale,coverage:body.coverage,acknowledge_verification_limit:body.acknowledge_verification_limit,created_at:new Date().toISOString(),manual_confirmation:true};if(body.conclusion==='accepted'&&thread.task.status!=='accepted'){thread.task_version++;thread.task.status='accepted';workspace.stages[0].tasks[0].status='accepted';}const response={submission:s,task_status:thread.task.status,task_version:thread.task_version,created:true,manual_confirmation:true};decisionReceipts[body.idempotency_key]=response;if(failDecision){failDecision=false;return r.abort('failed');}if(body.rationale==='刷新测试')workspace={...workspace,plan:{...workspace.plan,plan_id:'p2',revision:2},stages:[{...workspace.stages[0],tasks:[{...task,task_id:'t2',title:'新路线任务'}]}]};return r.fulfill({json:response});}
  saves.push(body);if(dropSave){dropSave=false;return r.abort('failed');}if(body.plan_id!==workspace.plan.plan_id)return r.fulfill({status:409,json:{message:'旧路线请求尚未成功，当前路线已变化'}});if(invalid){invalid=false;return r.fulfill({status:422,json:{message:'证据内容无效'}});}if(conflict){conflict=false;thread.version++;return r.fulfill({status:409,json:{message:'成果版本已变化'}});}
  let s=Object.values(submissions).find(v=>v.key===body.idempotency_key);if(!s){s={submission_id:'sub'+saves.length,project_id:'project',plan_id:body.plan_id,stage_id:body.stage_id,task_id:body.task_id,submission_no:thread.submissions.length+1,version:thread.version+1,note:body.note,repo_url:body.repo_url,evidence:body.evidence,legacy_evidence:[],artifact_kind:body.artifact_kind,parent_submission_id:body.parent_submission_id,content_hash:'hash',task_snapshot:{snapshot_status:'frozen',plan_id:'p',plan_revision:1,stage_id:'s',stage_title:stage.title,practice_project:practice,task:JSON.parse(JSON.stringify(task)),warning:null},evidence_grade:body.evidence.length?'reported':'insufficient',verification_available:false,source_check_available:false,review:null,created_at:new Date().toISOString(),key:body.idempotency_key};submissions[s.submission_id]=s;thread.submissions.push(s);thread.version++;if(!['accepted','awaiting_evidence'].includes(thread.task.status)){thread.task_version++;thread.task.status='awaiting_evidence';}}
  if(failSave){failSave=false;return r.abort('failed');}if(holdSave){holdSave=false;enteredSave();await new Promise(resolve=>{releaseSave=resolve;});}return r.fulfill({json:{thread,submission:s,replayed:false}});
 });
 await page.goto((process.env.STUDYPLAN_URL||'http://127.0.0.1:5174')+'/#practice');
 const panel=page.getByRole('region',{name:'成果提交与人工验收',exact:true});await panel.waitFor();
 const note=panel.getByLabel('成果说明原文',{exact:true});await note.fill('  我的实际成果🙂\n保留原格式。  ');await panel.getByLabel('成果资料分类').selectOption('architecture');await panel.getByRole('button',{name:'添加证据',exact:true}).click();const evidence=panel.getByRole('group',{name:'证据 1',exact:true});await evidence.getByLabel('证据类别').selectOption('external_report');await evidence.getByLabel('证据标题').fill(' 外部运行报告 ');await evidence.getByLabel('证据原文').fill(' 运行者报告：输出为42\n未由平台执行。 ');
 await page.getByLabel('实践任务',{exact:true}).selectOption('t-alt');await note.fill('另一个任务的本地成果');await page.getByLabel('实践任务',{exact:true}).selectOption('t');assert.equal(await note.inputValue(),'  我的实际成果🙂\n保留原格式。  ');assert.equal(await evidence.getByLabel('证据原文').inputValue(),' 运行者报告：输出为42\n未由平台执行。 ');
 await panel.getByRole('button',{name:'保存成果与证据',exact:true}).click();await panel.getByRole('button',{name:'重试原成果保存',exact:true}).waitFor();await note.fill('保存未知期间的新编辑');await panel.getByRole('button',{name:'重试原成果保存',exact:true}).click();await panel.getByText('已报告，未由平台核验',{exact:true}).waitFor();assert.deepEqual(saves[0],saves[1]);assert.equal(await note.inputValue(),'保存未知期间的新编辑');
 const detail=panel.locator('.submission-detail:visible');await detail.getByText('  我的实际成果🙂\n保留原格式。  ',{exact:true}).waitFor();await detail.getByLabel('人工决定',{exact:true}).selectOption('accepted');await detail.getByLabel('人工决定理由').fill('我对照实际记录检查了两个要求');const decide=detail.getByRole('button',{name:'记录人工决定',exact:true});assert.equal(await decide.isEnabled(),false);
 for(let i=0;i<2;i++){const group=detail.getByRole('group',{name:`验收要求 ${i+1}`,exact:true});await group.getByLabel('选择证据 1').check();await group.getByLabel('实际观察').fill('对应记录可说明此项要求');}
 await detail.getByLabel('我理解这是人工确认，平台没有独立运行代码或核验来源').check();await decide.click();await detail.getByRole('button',{name:'重试原人工决定',exact:true}).waitFor();await note.fill('人工决定期间继续编辑');await detail.getByRole('button',{name:'重试原人工决定',exact:true}).click();await detail.getByText('人工确认通过（未平台实测）',{exact:true}).waitFor();assert.deepEqual(decisions[0],decisions[1]);assert.equal(await note.inputValue(),'人工决定期间继续编辑');
 conflict=true;await panel.getByRole('button',{name:'保存成果与证据',exact:true}).click();await panel.getByText(/成果版本已变化/).waitFor();await panel.getByRole('button',{name:'读取当前成果记录',exact:true}).click();assert.equal(await note.inputValue(),'人工决定期间继续编辑');
 late=true;const reading=new Promise(resolve=>{enteredRead=resolve;});await panel.getByRole('button',{name:'读取当前成果记录',exact:true}).click();await reading;holdSave=true;const saving=new Promise(resolve=>{enteredSave=resolve;});await panel.getByRole('button',{name:'保存成果与证据',exact:true}).click();await saving;await note.fill('迟到响应后仍应保留的新文字');releaseSave();await panel.getByLabel('选择已保存成果').selectOption('sub4');releaseRead();assert.equal(await note.inputValue(),'迟到响应后仍应保留的新文字');
 invalid=true;await panel.getByRole('button',{name:'保存成果与证据',exact:true}).click();await panel.getByText(/证据内容无效/).waitFor();assert.equal(await panel.getByRole('button',{name:'保存成果与证据',exact:true}).isEnabled(),true);
 await panel.getByLabel('补充到已有成果').selectOption('sub1');await panel.getByRole('button',{name:'保存成果与证据',exact:true}).click();assert.equal(saves.at(-1).parent_submission_id,'sub1');
 await page.getByRole('button',{name:'读取成果资料归档',exact:true}).click();const archive=page.getByRole('region',{name:'成果资料归档',exact:true});await archive.getByRole('heading',{name:'架构',exact:true}).waitFor();assert.equal(await archive.getByText('待补充',{exact:true}).count(),5);await archive.getByRole('button',{name:/交付助手/}).click();await archive.getByRole('article',{name:'所选成果详情',exact:true}).getByText('人工确认通过（未平台实测）',{exact:true}).waitFor();await archive.getByRole('button',{name:'读取更早的成果资料',exact:true}).click();await archive.getByRole('button',{name:/旧成果（当时任务未记录）/}).click();const oldDetail=archive.getByRole('article',{name:'所选成果详情',exact:true});await oldDetail.getByText('旧记录保留的已核验等级，本批未重新实测',{exact:true}).waitFor();await oldDetail.getByText('旧报告未结构化原文',{exact:true}).waitFor();assert.equal(await oldDetail.getByLabel('人工决定',{exact:true}).count(),0);assert.equal(await note.inputValue(),'迟到响应后仍应保留的新文字');
 await panel.getByLabel('选择已保存成果').selectOption('sub6');await note.fill('旧路线还未保存的说明');await evidence.getByLabel('证据原文').fill('旧路线还未保存的证据');dropSave=true;await panel.getByRole('button',{name:'保存成果与证据',exact:true}).click();await panel.getByRole('button',{name:'重试原成果保存',exact:true}).waitFor();const unknownOldBody=saves.at(-1);await detail.getByLabel('人工决定理由').fill('刷新测试');await detail.getByRole('button',{name:'记录人工决定',exact:true}).click();const recovery=panel.getByRole('region',{name:'旧路线未保存的成果',exact:true});await recovery.waitFor();const recovered=await recovery.getByRole('textbox').first().inputValue();assert.ok(recovered.includes('旧路线还未保存的说明')&&recovered.includes('旧路线还未保存的证据'));assert.equal(await recovery.getByRole('textbox').first().getAttribute('readonly'),'');await recovery.getByRole('button',{name:'复制旧成果与证据',exact:true}).first().click();assert.equal(await page.evaluate(()=>window.submissionCopied),recovered);assert.equal(await note.inputValue(),'');await recovery.getByRole('button',{name:'核对旧请求（原内容与原请求标识）',exact:true}).click();await recovery.getByText(/旧路线请求尚未成功/).waitFor();assert.deepEqual(saves.at(-1),unknownOldBody);assert.equal(await recovery.getByRole('button',{name:'核对旧请求（原内容与原请求标识）',exact:true}).count(),0);
 assert.equal(unexpected,0);assert.equal(await page.evaluate(()=>JSON.stringify(localStorage).includes('迟到响应后')),false);fs.mkdirSync(path.resolve(__dirname,'../../var/v2-g4'),{recursive:true});await recovery.scrollIntoViewIfNeeded();await page.screenshot({path:path.resolve(__dirname,'../../var/v2-g4/submission-mock.png'),fullPage:true});
 console.log('PASS: saved raw evidence, manual coverage/ack, exact retry bodies, CAS/422/late editor protection, supplemental lineage and truthful Outcome groups');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
