import { useEffect, useRef, useState } from 'react';
import { ApiError } from '../../api/client';
import { practiceChangeApi } from '../../api/practiceChangeClient';
import type { PracticeChangeContextView, PracticeChangeDecisionRequest, PracticeChangePreviewView, PracticeChangeProjectView, PracticeChangeRequest, PracticeChangeResultView, PracticeChangeTaskRequest, PracticeChangeTaskView } from '../../api/practiceChangeClient';

type TaskEdit=Omit<PracticeChangeTaskRequest,'in_scope'|'out_scope'|'acceptance'> & {in_scope:string;out_scope:string;acceptance:string};
type Form={projectId:string;title:string;idea:string;repo:string;stageId:string;tasks:TaskEdit[];policy:PracticeChangeRequest['copy_policy']};
const roles={core:'核心',supporting:'支撑',extension:'延伸'};
const message=(e:unknown)=>e instanceof Error?e.message:'操作未能核对，请保留输入后重试。';
const definiteRejection=(e:unknown):e is ApiError=>e instanceof ApiError&&[400,401,403,404,409,422].includes(e.status);
const lines=(s:string)=>s.split(/\r?\n/).filter(v=>v.trim());
const taskEdit=(t:PracticeChangeTaskView):TaskEdit=>({operation:'update',client_key:crypto.randomUUID(),task_id:t.task_id,stage_id:t.stage_id,title:t.title,goal:t.goal,in_scope:t.in_scope.join('\n'),out_scope:t.out_scope.join('\n'),acceptance:t.acceptance.join('\n'),knowledge_links:t.knowledge_links.map(n=>({node_id:n.node_id,role:n.role}))});
function initialForm(c:PracticeChangeContextView,p=c.practice_projects[0]):Form|null{return p?{projectId:p.practice_project_id,title:p.title,idea:p.idea,repo:p.repo_url||'',stageId:c.stages[0]?.stage_id||'',tasks:[],policy:'keep_history_only'}:null;}
function ProjectFacts({value}:{value:PracticeChangeProjectView}) {return <><h4>{value.title}</h4><p>{value.idea}</p><p>仓库地址：{value.repo_url||'未填写'}</p><p>项目状态：{({idea:'设想',planned:'计划中',in_progress:'进行中',completed:'已完成'} as Record<string,string>)[value.status]||value.status} · 第 {value.version} 版</p></>;}
function TaskFacts({value,stageTitle}:{value:PracticeChangeTaskView;stageTitle?:string}) {return <><h5>{value.title}</h5><p>所属阶段：{stageTitle||value.stage_key} · 阶段内第 {value.order_index+1} 项任务</p><p>{value.goal}</p>{(['in_scope','out_scope','acceptance'] as const).map(k=><div key={k}><strong>{{in_scope:'实施范围',out_scope:'范围之外',acceptance:'验收要求'}[k]}</strong><ul>{value[k].map((v,i)=><li key={i}>{v}</li>)}</ul></div>)}<strong>关联知识</strong><ul>{value.knowledge_links.map(n=><li key={n.node_id}><span>{n.title}（{roles[n.role]}）</span> · 内容第 {n.content_version} 版</li>)}</ul><p>任务状态：{({pending:'待开始',planned:'待开始',in_progress:'进行中',accepted:'已验收'} as Record<string,string>)[value.status]||value.status} · 任务第 {value.version} 版</p><details><summary>任务版本与归属记录</summary><p>任务标识：{value.task_id}</p><p>任务键：{value.stable_key}</p><p>主项目标识：{value.practice_project_id}</p></details></>;}

export function PracticeChangePanel({project,onPublished}:{project:string;onPublished?:()=>Promise<void>|void}) {
 const [open,setOpen]=useState(false),[context,setContext]=useState<PracticeChangeContextView|null>(null),[form,setForm]=useState<Form|null>(null),[preview,setPreview]=useState<PracticeChangePreviewView|null>(null),[result,setResult]=useState<PracticeChangeResultView|null>(null);
 const [pendingPreview,setPendingPreview]=useState<PracticeChangeRequest|null>(null),[pendingDecision,setPendingDecision]=useState<{id:string;action:'confirm'|'cancel';body:PracticeChangeDecisionRequest}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[ack,setAck]=useState(false),[conflict,setConflict]=useState(false);
 const alive=useRef(true),readSequence=useRef(0);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;readSequence.current++;};},[]);
 async function read(){const ticket=++readSequence.current;setBusy(true);setError('');try{const c=await practiceChangeApi.context(project);if(alive.current&&ticket===readSequence.current){setContext(c);setForm(old=>old||initialForm(c));if(conflict){setPendingPreview(null);setConflict(false);}}}catch(e){if(alive.current)setError(message(e));}finally{if(alive.current&&ticket===readSequence.current)setBusy(false);}}
 useEffect(()=>{if(open&&!context)void read();},[open]);
 function change(fn:(f:Form)=>Form){setForm(old=>old?fn(old):old);}
 function edit(index:number,fn:(t:TaskEdit)=>TaskEdit){change(f=>({...f,tasks:f.tasks.map((t,i)=>i===index?fn(t):t)}));}
 async function submit(body:PracticeChangeRequest){readSequence.current++;setPendingPreview(body);setBusy(true);setError('');setConflict(false);try{const p=await practiceChangeApi.preview(project,body);if(alive.current){setPreview(p);setResult(null);setAck(false);setPendingPreview(null);}}catch(e){if(alive.current){setError(message(e));setConflict(e instanceof ApiError&&e.status===409);if(definiteRejection(e)&&e.status!==409)setPendingPreview(null);}}finally{if(alive.current)setBusy(false);}}
 function makePreview(){if(!form||!context)return;const changes=form.tasks.map(t=>({...t,in_scope:lines(t.in_scope),out_scope:lines(t.out_scope),acceptance:lines(t.acceptance)}));
  if(!form.title.trim()||Array.from(form.title).length>200||!form.idea.trim()||Array.from(form.idea).length<10||Array.from(form.idea).length>4000||changes.some(t=>!t.title.trim()||!t.goal.trim()||Array.from(t.title).length>200||Array.from(t.goal).length>2000||[t.in_scope,t.out_scope,t.acceptance].some(a=>!a.length||a.length>20||a.some(v=>Array.from(v).length>2000))||!t.knowledge_links.some(n=>n.role==='core')||t.knowledge_links.length>30)){setError('请填写完整主项目与任务要求，每个修改任务至少关联一个核心知识；每组范围或验收要求各行填写一项。');return;}
  void submit({plan_id:context.plan_id,practice_project_id:form.projectId,title:form.title,idea:form.idea,repo_url:form.repo||null,task_changes:changes,expected_version:context.version,copy_policy:form.policy,idempotency_key:crypto.randomUUID()});
 }
 async function decide(pending:NonNullable<typeof pendingDecision>){readSequence.current++;setPendingDecision(pending);setBusy(true);setError('');try{const r=await practiceChangeApi.decide(project,pending.id,pending.action,pending.body);if(!alive.current)return;setResult(r);setPreview(old=>old?.proposal_id===pending.id?{...old,status:r.status}:old);setPendingDecision(null);setAck(false);if(r.action==='confirm'){try{await onPublished?.();}catch(e){if(alive.current)setError(`调整已发布，工作区刷新未完成：${message(e)} 请重新读取工作区；不会再次发布。`);}}}catch(e){if(alive.current){setError(message(e));if(definiteRejection(e)){setPendingDecision(null);setAck(false);}}}finally{if(alive.current)setBusy(false);}}
 function newDecision(action:'confirm'|'cancel'){if(preview)void decide({id:preview.proposal_id,action,body:{expected_version:preview.base_version,preview_hash:preview.preview_hash,acknowledge_warnings:action==='confirm'&&ack,idempotency_key:crypto.randomUUID()}});}
 async function refreshPreview(){if(!preview)return;setBusy(true);setError('');try{const p=await practiceChangeApi.get(project,preview.proposal_id);if(alive.current){setPreview(p);setAck(false);}}catch(e){if(alive.current)setError(message(e));}finally{if(alive.current)setBusy(false);}}
 const tasks=context?.tasks.filter(t=>t.practice_project_id===form?.projectId&&t.stage_id===form?.stageId)||[];
 const staleProject=!!(form&&context&&!context.practice_projects.some(p=>p.practice_project_id===form.projectId));
 const staleStage=!!(form&&context&&!context.stages.some(s=>s.stage_id===form.stageId));
 const staleTasks=!!(form&&context&&form.tasks.some(t=>!context.stages.some(s=>s.stage_id===t.stage_id)||(t.operation==='update'&&!context.tasks.some(current=>current.task_id===t.task_id&&current.practice_project_id===form.projectId&&current.stage_id===t.stage_id))));
 return <section className="panel practice-change"><button className="practice-disclosure" aria-expanded={open} onClick={()=>setOpen(v=>!v)}>调整主项目与阶段任务</button>{open&&<>
  <p>沿用路线中的候选主项目，或按自己的方向调整设想和任务。这里保存的是实践设计，不能代表实现、测试或验收；预览不会调用模型，明确确认后才发布新路线。</p>
  <button className="btn" disabled={busy} onClick={()=>void read()}>读取当前实践设计</button>{context&&<p>当前读取：路线第 {context.revision} 版。重新读取会保留本地输入；路线变化后请核对任务归属再预览。</p>}
  {context&&!context.practice_projects.length&&<p>当前路线没有关联的主项目，请先在路线中安排实践项目与任务。</p>}
  {form&&context&&<div className="practice-form"><label>选择主项目<select aria-label="选择主项目" value={form.projectId} onChange={e=>{const p=context.practice_projects.find(v=>v.practice_project_id===e.target.value);if(p)setForm(staleProject?{...form,projectId:p.practice_project_id}:initialForm(context,p));}} disabled={!!pendingPreview||!!pendingDecision}>{staleProject&&<option value={form.projectId} disabled>旧主项目已不在当前路线，请选择</option>}{context.practice_projects.map(p=><option key={p.practice_project_id} value={p.practice_project_id}>{p.title}</option>)}</select></label>
   {staleProject&&<p role="status">原主项目已不在当前路线，请明确选择当前主项目；本地文字会继续保留。</p>}
   {!staleProject&&staleTasks&&<p role="status">部分本地任务编辑仍属于旧路线，请保留文字后撤回这些编辑，再选择当前任务。</p>}
   <label>主项目标题<input aria-label="主项目标题" maxLength={200} value={form.title} onChange={e=>change(f=>({...f,title:e.target.value}))}/></label><label>主项目设想<textarea aria-label="主项目设想" rows={4} value={form.idea} onChange={e=>change(f=>({...f,idea:e.target.value}))}/></label><label>仓库地址（可选）<input aria-label="仓库地址（可选）" value={form.repo} onChange={e=>change(f=>({...f,repo:e.target.value}))}/></label><p className="form-note">仓库地址仅作为元数据保存，不会访问仓库，也不代表来源已验证。</p>
   <label>调整所属阶段<select aria-label="调整所属阶段" value={form.stageId} onChange={e=>change(f=>({...f,stageId:e.target.value}))}>{staleStage&&<option value={form.stageId} disabled>旧阶段已不在当前路线，请选择</option>}{context.stages.map(s=><option key={s.stage_id} value={s.stage_id}>{s.title}</option>)}</select></label>
   {staleStage&&<p role="status">原阶段已不在当前路线，请明确选择当前阶段；已有任务编辑不会自动改归属。</p>}
   <div className="chips">{tasks.map(t=><button className="btn" key={t.task_id} disabled={form.tasks.some(v=>v.task_id===t.task_id)||form.tasks.length>=30} onClick={()=>change(f=>({...f,tasks:[...f.tasks,taskEdit(t)]}))}>编辑任务：{t.title}</button>)}<button className="btn" disabled={!form.stageId||staleStage||form.tasks.length>=30} onClick={()=>change(f=>({...f,tasks:[...f.tasks,{operation:'add',client_key:crypto.randomUUID(),task_id:null,stage_id:f.stageId,title:'',goal:'',in_scope:'',out_scope:'',acceptance:'',knowledge_links:[]}]}))}>添加阶段任务</button></div>
   {form.tasks.map((t,index)=><fieldset key={t.client_key} aria-label={`编辑任务 ${index+1}`}><legend>{t.operation==='add'?'新增':'修订'}任务 {index+1} · {context.stages.find(s=>s.stage_id===t.stage_id)?.title||'旧阶段，请核对'}</legend><label>任务标题<input aria-label="任务标题" value={t.title} onChange={e=>edit(index,v=>({...v,title:e.target.value}))}/></label><label>交付物与任务目标<textarea aria-label="交付物与任务目标" rows={3} value={t.goal} onChange={e=>edit(index,v=>({...v,goal:e.target.value}))}/></label>
    {(['in_scope','out_scope','acceptance'] as const).map(k=><label key={k}>{{in_scope:'实施范围',out_scope:'范围之外',acceptance:'验收要求'}[k]}（每行一项）<textarea aria-label={{in_scope:'实施范围',out_scope:'范围之外',acceptance:'验收要求'}[k]} rows={2} value={t[k]} onChange={e=>edit(index,v=>({...v,[k]:e.target.value}))}/></label>)}
    <h4>选择本路线中的知识与角色</h4>{context.knowledge_options.map(n=>{const link=t.knowledge_links.find(v=>v.node_id===n.node_id);return <div className="practice-knowledge" key={n.node_id}><label><input aria-label={`选择知识：${n.title}`} type="checkbox" checked={!!link} onChange={e=>edit(index,v=>({...v,knowledge_links:e.target.checked?[...v.knowledge_links,{node_id:n.node_id,role:'core'}]:v.knowledge_links.filter(x=>x.node_id!==n.node_id)}))}/>{n.title} · 内容第 {n.content_version} 版</label><select aria-label={`知识角色：${n.title}`} disabled={!link} value={link?.role||'core'} onChange={e=>edit(index,v=>({...v,knowledge_links:v.knowledge_links.map(x=>x.node_id===n.node_id?{...x,role:e.target.value as typeof x.role}:x)}))}>{Object.entries(roles).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>;})}<p className="form-note">至少一个核心知识。知识关联是任务要求，不代表已经掌握。</p><button className="text-button" onClick={()=>change(f=>({...f,tasks:f.tasks.filter((_,i)=>i!==index)}))}>撤回这项本地编辑</button></fieldset>)}
   <label>私人资料沿用策略<select aria-label="私人资料沿用策略" value={form.policy} onChange={e=>change(f=>({...f,policy:e.target.value as Form['policy']}))}><option value="keep_history_only">只保留旧路线历史，不复制私人资料</option><option value="copy_active">沿用仍适用的私人资料选择，保留原来源</option></select></label>
   <button className="btn primary" disabled={busy||staleProject||staleStage||staleTasks||!!pendingPreview||!!pendingDecision||preview?.status==='pending'} onClick={makePreview}>生成实践调整预览</button>{pendingPreview&&!conflict&&<button className="btn" disabled={busy} onClick={()=>void submit(pendingPreview)}>重试原预览</button>}
  </div>}
  {error&&<p role="alert">{error} {conflict?'请读取当前实践设计，输入将保留。':pendingPreview||pendingDecision?'结果未能确认，请重试原请求；不会自动重派。':''}</p>}
  {preview&&<section className="practice-preview" aria-label="实践调整预览"><h3>实践调整预览</h3><p>基于路线第 {preview.base_revision} 版；此处展示原预览内容，编辑框后来输入不会改变这次确认。</p><div className="practice-diff"><div><h4>调整前主项目</h4><ProjectFacts value={preview.before}/></div><div><h4>调整后主项目</h4><ProjectFacts value={preview.after}/></div></div>
   {preview.task_changes.map((delta,i)=><article className="practice-task-delta" key={delta.after.task_id}><h4>{{update:'修订任务',add:'新增任务',rebind:'随主项目沿用任务'}[delta.operation]} {i+1}</h4><div className="practice-diff"><div><h5>调整前</h5>{delta.before?<TaskFacts value={delta.before} stageTitle={context?.stages.find(s=>s.stage_id===delta.before!.stage_id)?.title}/>:<p>原路线没有这项任务。</p>}</div><div><h5>调整后</h5><TaskFacts value={delta.after} stageTitle={context?.stages.find(s=>s.stage_id===delta.after.stage_id)?.title}/></div></div></article>)}
   <p>重新关联任务 {preview.impact.cloned_task_count} 项；已有开始或验收记录的任务 {preview.impact.started_task_count} 项。保留原文 {preview.impact.prompt_revision_count} 版、总结 {preview.impact.summary_count} 条和旧学习位置 {preview.impact.exposure_count} 个。私人资料选择 {preview.impact.private_binding_count} 条。</p><p>{preview.impact.new_exposures_reset?'新路线学习位置从未开始状态建立；旧学习记录仍属于旧路线。':'学习位置影响请以提示为准。'} {preview.copy_policy==='copy_active'?'按明确策略沿用适用私人资料，不作为阅读证据。':'私人资料只留在旧路线历史。'}</p>
   {preview.warnings.length>0&&<><h4>发布前请逐条核对</h4><ul>{preview.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul></>}
   {preview.status==='pending'&&<><label className="practice-ack"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)} aria-label="我已阅读差异和全部提示，同意发布这次调整"/>我已阅读差异和全部提示，同意发布这次调整</label><div className="chips"><button className="btn primary" disabled={busy||!ack||!!pendingDecision} onClick={()=>newDecision('confirm')}>确认并发布实践调整</button><button className="btn" disabled={busy||!!pendingDecision} onClick={()=>newDecision('cancel')}>取消这次调整</button><button className="btn" disabled={busy} onClick={()=>void refreshPreview()}>核对这次预览状态</button></div></>}
   {pendingDecision&&<button className="btn" disabled={busy} onClick={()=>void decide(pendingDecision)}>{pendingDecision.action==='confirm'?'重试原确认':'重试原取消'}</button>}
  </section>}
  {result&&<p role="status">{result.status==='confirmed'?`已发布路线第 ${result.revision} 版。旧任务、原文与成果历史保留；不会自动将旧原文保存到新任务。`:'这次调整已取消，当前路线未被改变。'}</p>}
 </>}</section>;
}
