import {useEffect,useRef,useState} from 'react';
import {ApiError} from '../../api/client';
import {assistantApi} from '../../api/assistantClient';
import type {AssistantIntent,AssistantStart,AssistantSend,AssistantSave,AssistantCancel,Conversation,ConversationSummary} from '../../api/assistantClient';
import {assistantBlocked,currentAssistantDraft,latestAssistantRun,mergeConversation,mergeAssistantHistory,terminalAssistant} from './assistantState';
type Buffer = {text:string;intent:AssistantIntent;formal:string;formalDirty:boolean;consent:boolean;error:string;busy:boolean;historyBusy?:boolean;saveConflict?:boolean;send?:AssistantSend;save?:AssistantSave;cancel?:AssistantCancel};
const fresh = ():Buffer => ({text:'',intent:'work_draft',formal:'',formalDirty:false,consent:false,error:'',busy:false});
export function useAssistant(project:string,actor:string,onSaved:()=>Promise<void>,planId?:string) {
  const [records,setRecords]=useState<Record<string,Conversation>>({}),[buffers,setBuffers]=useState<Record<string,Buffer>>({}),[selected,setSelected]=useState(''),[open,setOpen]=useState(false),[items,setItems]=useState<ConversationSummary[]>([]),[cursor,setCursor]=useState<string|null>(null),[listError,setListError]=useState(''),[starting,setStarting]=useState(false),[startPending,setStartPending]=useState<AssistantStart|null>(null);
  const [listScope,setListScope]=useState(''),[listLoading,setListLoading]=useState(false),[listLoaded,setListLoaded]=useState(false);
  const listBusy=useRef(false);
  const scopeKey=JSON.stringify([project,actor]);
  const listReady=!!project&&listScope===scopeKey;
  const recordsRef=useRef<Record<string,Conversation>>({});
  const epoch=useRef(0), busy=useRef(new Set<string>()), createBusy=useRef(false), tickets=useRef<Record<string,number>>({});
  useEffect(()=>{epoch.current++;recordsRef.current={};setRecords({});setBuffers({});setSelected('');setOpen(false);setItems([]);setCursor(null);setListError('');setStartPending(null);setStarting(false);setListScope(scopeKey);setListLoaded(false);setListLoading(false);listBusy.current=false;busy.current.clear();createBusy.current=false;},[project,actor]);
  function update(id:string,fn:(b:Buffer)=>Buffer){setBuffers(old=>({...old,[id]:fn(old[id]||fresh())}));}
  function put(c:Conversation){c=mergeConversation(recordsRef.current[c.conversation_id],c);recordsRef.current={...recordsRef.current,[c.conversation_id]:c};setRecords(recordsRef.current);setBuffers(old=>{const b=old[c.conversation_id]||fresh();return {...old,[c.conversation_id]:{...b,...(!b.formalDirty?{formal:currentAssistantDraft(c)}:{})}};});}
  async function read(id=selected,explicit=true){if(!id)return;const e=epoch.current,t=tickets.current[id]=(tickets.current[id]||0)+1;try{const c=await assistantApi.read(project,id);if(e===epoch.current&&tickets.current[id]===t){put(c);update(id,b=>({...b,error:'',...(explicit?{saveConflict:false}:{})}));}}catch(err){if(e===epoch.current)update(id,b=>({...b,error:`读取未完成：${(err as Error).message}。原文保留；刷新只读取状态。`}));}}
  async function earlier(){const id=selected,before=recordsRef.current[id]?.message_cursor;if(!id||before==null||buffers[id]?.historyBusy)return;const e=epoch.current;update(id,b=>({...b,historyBusy:true}));try{const page=await assistantApi.read(project,id,before);if(e!==epoch.current)return;const current=recordsRef.current[id];if(current&&current.message_cursor===before){const merged=mergeAssistantHistory(current,page);recordsRef.current={...recordsRef.current,[id]:merged};setRecords(recordsRef.current);}}catch(err){if(e===epoch.current)update(id,b=>({...b,error:`较早消息读取未完成：${(err as Error).message}。当前草稿保留，请手动再读取。`}));}finally{if(e===epoch.current)update(id,b=>({...b,historyBusy:false}));}}
  async function resume(id:string){setSelected(id);setOpen(true);await read(id);}
  async function start(body:Omit<AssistantStart,'idempotency_key'>|AssistantStart){if(createBusy.current)return;if(startPending&&!('idempotency_key' in body)){setOpen(true);return;}createBusy.current=true;setStarting(true);const request='idempotency_key' in body?body:{...body,idempotency_key:crypto.randomUUID()};setStartPending(request);const e=epoch.current;try{const c=await assistantApi.create(project,request);if(e===epoch.current){put(c);setSelected(c.conversation_id);setOpen(true);setStartPending(null);setListError('');}}catch(err){if(e===epoch.current){setListError(`创建结果未确认：${(err as Error).message}。请使用原操作核对，避免重复创建。`);setOpen(true);}}finally{if(e===epoch.current){createBusy.current=false;setStarting(false);}}}
  async function list(more=false){if(!listReady||listBusy.current)return;listBusy.current=true;setListLoading(true);const e=epoch.current;try{const result=await assistantApi.list(project,more?cursor||undefined:undefined);if(e===epoch.current){setItems(old=>more?[...old,...result.items.filter(c=>!old.some(o=>o.conversation_id===c.conversation_id))]:result.items);setCursor(result.next_cursor);setListError('');setListLoaded(true);}}catch(err){if(e===epoch.current)setListError((err as Error).message);}finally{if(e===epoch.current){listBusy.current=false;setListLoading(false);}}}
  async function mutate(kind:'send'|'save'|'cancel',body:AssistantSend|AssistantSave|AssistantCancel){const id=selected;if(!id||busy.current.has(id))return;const e=epoch.current;busy.current.add(id);tickets.current[id]=(tickets.current[id]||0)+1;update(id,b=>({...b,busy:true,error:'',[kind]:body}));try{const c=await (kind==='send'?assistantApi.send(project,id,body as AssistantSend):kind==='save'?assistantApi.save(project,id,body as AssistantSave):assistantApi.cancel(project,id,body as AssistantCancel));if(e!==epoch.current)return;put(c);update(id,b=>({...b,[kind]:undefined,consent:false,...(kind==='send'&&b.text===(body as AssistantSend).content?{text:'',intent:'question' as const}:{}),...(kind==='save'?{saveConflict:false,formalDirty:false,formal:(body as AssistantSave).content}:{})}));if(kind==='save'){try{await onSaved();}catch{if(e===epoch.current)update(id,b=>({...b,error:'正式原文已保存；工作区刷新待核对，请刷新工作区。'}));}}}catch(err){if(e===epoch.current)update(id,b=>({...b,error:`${(err as Error).message} 原文保留。${err instanceof ApiError&&err.status===409?'版本或状态冲突，请先读取核对；不会自动覆盖。':'结果未确认，请先刷新核对，原操作可用同一键查回。'}`, ...(err instanceof ApiError&&err.status===409?{[kind]:undefined,...(kind==='save'?{saveConflict:true}:{})}:{})}));}finally{if(e===epoch.current){busy.current.delete(id);tickets.current[id]=(tickets.current[id]||0)+1;update(id,b=>({...b,busy:false}));}}}
  const stored=records[selected],conversation=stored&&planId&&stored.plan_id!==planId?{...stored,read_only:true}:stored,buffer=buffers[selected]||fresh(),run=latestAssistantRun(conversation);
  useEffect(()=>{if(selected)void read(selected,false);},[planId]);
  useEffect(()=>{if(!conversation||!run?.run_id||terminalAssistant.has(run.run_status||''))return;const timer=setTimeout(()=>void read(conversation.conversation_id,false),document.hidden?15000:1500);return()=>clearTimeout(timer);},[conversation,run?.run_status]);
  const dirty=Object.values(buffers).some(b=>!!b.text||b.formalDirty);
  useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
  return {conversation,buffer,open,setOpen,items,cursor,listError,listScope,listReady,listLoading,listLoaded,starting,startPending,start,resume,list,read,earlier,run,blocked:assistantBlocked(conversation),update:(patch:Partial<Buffer>)=>update(selected,b=>({...b,...patch})),send:(body:AssistantSend)=>mutate('send',body),save:(body:AssistantSave)=>mutate('save',body),cancel:(body:AssistantCancel)=>mutate('cancel',body),clear:()=>{epoch.current++;recordsRef.current={};setRecords({});setBuffers({});setSelected('');setOpen(false);setItems([]);setCursor(null);setListError('');setStartPending(null);setListScope('');setListLoading(false);setListLoaded(false);listBusy.current=false;}};
}
export type AssistantController = ReturnType<typeof useAssistant>;
